packages:
  - 'dotcom-rendering'
  - 'ab-testing'
  - 'ab-testing/*'
allowBuilds:
  '@swc/core': true
  esbuild: true
  nice-napi: true
  unrs-resolver: false # This postinstall is just a workaround for an npm issue so we don't need it https://github.com/unrs/unrs-resolver/pull/66
blockExoticSubdeps: true
catalog:
  '@aws-sdk/client-s3': 3.995.0
  '@aws-sdk/client-ssm': 3.995.0
  '@guardian/cdk': 63.6.1
  '@guardian/eslint-config': 16.0.0
  '@guardian/tsconfig': 1.0.1
  '@rollup/plugin-commonjs': 29.0.0
  '@rollup/plugin-json': 6.1.0
  '@rollup/plugin-node-resolve': 16.0.3
  '@types/aws-lambda': 8.10.158
  '@types/node': 24.12.4
  aws-cdk: 2.1126.0
  aws-cdk-lib: 2.257.0
  constructs: 10.6.0
  esbuild: 0.28.1
  eslint: 10.6.0
  rollup: 4.59.0
  rollup-plugin-esbuild: 6.2.1
  superstruct: 2.0.2
  tslib: 2.6.2
  type-fest: 4.21.0
  typescript: 6.0.3
minimumReleaseAge: 2880 # 2 day minimum package version age
minimumReleaseAgeExclude:
  - '@guardian/*'
