# This container is used in our CICD pipelines for running E2E and regression tests.
# Keep the Node version in sync with `.nvmrc`
FROM node:18.17.0-alpine

WORKDIR /opt/app/dotcom-rendering/dotcom-rendering

# Expects the file layout created by `make riffraff-bundle`
COPY ./dotcom-rendering/target /opt/app/dotcom-rendering/dotcom-rendering

EXPOSE 9000

ENV DISABLE_LOGGING_AND_METRICS=true
ENV NODE_ENV=production

ENTRYPOINT ["node", "rendering/dist/server.js"]
