// flow-typed signature: 62d23317a3139d83adc4682389c2024e
// flow-typed version: <<STUB>>/columnify_v^1.5.4/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'columnify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'columnify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'columnify/columnify' {
  declare module.exports: any;
}

declare module 'columnify/utils' {
  declare module.exports: any;
}

declare module 'columnify/width' {
  declare module.exports: any;
}

// Filename aliases
declare module 'columnify/columnify.js' {
  declare module.exports: $Exports<'columnify/columnify'>;
}
declare module 'columnify/index' {
  declare module.exports: $Exports<'columnify'>;
}
declare module 'columnify/index.js' {
  declare module.exports: $Exports<'columnify'>;
}
declare module 'columnify/utils.js' {
  declare module.exports: $Exports<'columnify/utils'>;
}
declare module 'columnify/width.js' {
  declare module.exports: $Exports<'columnify/width'>;
}
