// flow-typed signature: 49d0251545d86f5931dfb79e396004ec
// flow-typed version: <<STUB>>/curlyquotes_v^1.3.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'curlyquotes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'curlyquotes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'curlyquotes/dist/curlyquotes.es' {
  declare module.exports: any;
}

declare module 'curlyquotes/dist/curlyquotes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'curlyquotes/dist/curlyquotes.es.js' {
  declare module.exports: $Exports<'curlyquotes/dist/curlyquotes.es'>;
}
declare module 'curlyquotes/dist/curlyquotes.js' {
  declare module.exports: $Exports<'curlyquotes/dist/curlyquotes'>;
}
