// flow-typed signature: 007cbc248ce213fa29a528e7bcec1aa2
// flow-typed version: <<STUB>>/desvg-loader_v^0.1.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'desvg-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'desvg-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'desvg-loader/preact' {
  declare module.exports: any;
}

declare module 'desvg-loader/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'desvg-loader/preact.js' {
  declare module.exports: $Exports<'desvg-loader/preact'>;
}
declare module 'desvg-loader/react.js' {
  declare module.exports: $Exports<'desvg-loader/react'>;
}
