// flow-typed signature: 37c204ad2ff4b207d688d2a9af201006
// flow-typed version: <<STUB>>/emotion-server_v^8.0.8/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emotion-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emotion-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emotion-server/lib/index' {
  declare module.exports: any;
}

declare module 'emotion-server/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emotion-server/lib/index.js' {
  declare module.exports: $Exports<'emotion-server/lib/index'>;
}
declare module 'emotion-server/src/index.js' {
  declare module.exports: $Exports<'emotion-server/src/index'>;
}
