#!/usr/bin/env node

const execa = require('execa');
const chalk = require('chalk');
const fs = require('fs');

// execa
execa('git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD', {
    shell: true,
})
    .then((result) => {
        const changedFiles = result.stdout.split('\n');

        if (changedFiles.includes('.nvmrc')) {
            const nvmrcVersion = fs.readFileSync('.nvmrc');

            console.log(
                `${chalk.red(
                    `This application now requires Node v${nvmrcVersion}. Switch to the latest version using \`nvm install\` or download from nodejs.org. Then run \`make reinstall\`.`,
                )}`,
            );
        } else if (changedFiles.includes('yarn.lock')) {
            console.log(
                `${chalk.red(
                    'This application has new dependencies. Running `make install`...',
                )}`,
            );

            return execa('make', ['install'], {
                stdio: 'inherit',
            });
        }

        return Promise.resolve();
    })
    .catch((e) => {
        console.log(`\n${e}\n`);
        process.exit(1);
    });
