import type { Meta, StoryObj } from '@storybook/react-webpack5';
import { CricketMatchHeader } from './CricketMatchHeader';

const meta = {
	component: CricketMatchHeader,
} satisfies Meta<typeof CricketMatchHeader>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Fixture = {
	args: {
		edition: 'UK',
		match: {
			kind: 'Fixture',
			series: 'Ashes 2025–2026',
			competition: 'Second Test Match',
			venue: 'Brisbane Cricket Ground',
			matchDate: new Date('2026-01-26'),
			homeTeam: {
				paID: 'f7f611a1-e667-2aa2-c3e0-6dbc6981cfa4',
				lineup: [
					'Usman Khawaja',
					'David Warner',
					'Marnus Labuschagne',
					'Steve Smith',
					'Travis Head',
					'Cameron Green',
					'Alex Carey',
					'Pat Cummins',
					'Mitchell Starc',
					'Nathan Lyon',
					'Josh Hazlewood',
				],
				name: 'Australia',
			},
			awayTeam: {
				paID: 'a359844f-fc07-9cfa-d4cc-9a9ac0d5d075',
				lineup: [
					'Zak Crawley',
					'Ben Duckett',
					'Ollie Pope',
					'Joe Root',
					'Harry Brook',
					'Ben Stokes',
					'Jamie Smith',
					'Chris Woakes',
					'Gus Atkinson',
					'Mark Wood',
					'Shoaib Bashir',
				],
				name: 'England',
			},
			innings: [],
		},
	},
} satisfies Story;

export const Live = {
	args: {
		edition: 'UK',
		match: {
			...Fixture.args.match,
			kind: 'Live',
			day: 2,
			innings: [
				{
					declared: false,
					forfeited: false,
					battingTeam: 'Australia',
					description: 'Australia first innings',
					batters: [],
					bowlers: [],
					extras: {
						byes: 2,
						legByes: 1,
						noBalls: 1,
						penalties: 0,
						wides: 0,
					},
					inningsTotals: {
						runs: 169,
						overs: '20.0',
						wickets: 3,
						extras: 4,
					},
					fallOfWickets: [],
				},
				{
					declared: false,
					forfeited: false,
					battingTeam: 'England',
					description: 'England first innings',
					batters: [],
					bowlers: [],
					extras: {
						byes: 1,
						legByes: 1,
						noBalls: 0,
						penalties: 0,
						wides: 0,
					},
					inningsTotals: {
						runs: 173,
						overs: '19.3',
						wickets: 3,
						extras: 0,
					},
					fallOfWickets: [
						{ order: 1, name: 'Zak Crawley', runs: 67 },
						{ order: 2, name: 'Ben Duckett', runs: 145 },
						{ order: 3, name: 'Ollie Pope', runs: 173 },
					],
				},
			],
		},
	},
} satisfies Story;

export const LiveYetToBat = {
	name: 'Live (Team yet to bat)',
	args: {
		edition: 'UK',
		match: {
			...Fixture.args.match,
			kind: 'Live',
			day: 2,
			innings: [
				{
					declared: false,
					forfeited: false,
					battingTeam: 'Australia',
					description: 'Australia first innings',
					batters: [],
					bowlers: [],
					extras: {
						byes: 0,
						legByes: 0,
						noBalls: 0,
						penalties: 0,
						wides: 0,
					},
					inningsTotals: {
						runs: 169,
						overs: '20.0',
						wickets: 10,
						extras: 0,
					},
					fallOfWickets: [
						{ order: 1, name: 'David Warner', runs: 23 },
						{ order: 2, name: 'Usman Khawaja', runs: 45 },
						{ order: 3, name: 'Marnus Labuschagne', runs: 112 },
						{ order: 4, name: 'Steve Smith', runs: 169 },
						{ order: 5, name: 'Travis Head', runs: 169 },
						{ order: 6, name: 'Cameron Green', runs: 169 },
						{ order: 7, name: 'Alex Carey', runs: 169 },
						{ order: 8, name: 'Pat Cummins', runs: 169 },
						{ order: 9, name: 'Mitchell Starc', runs: 169 },
						{ order: 10, name: 'Nathan Lyon', runs: 169 },
					],
				},
			],
		},
	},
} satisfies Story;

export const Result = {
	args: {
		edition: 'UK',
		match: {
			...Fixture.args.match,
			kind: 'Result',
			day: 4,
			innings: [
				{
					declared: false,
					forfeited: false,
					battingTeam: 'Australia',
					description: 'Australia first innings',
					batters: [],
					bowlers: [],
					extras: {
						byes: 4,
						legByes: 3,
						noBalls: 2,
						penalties: 0,
						wides: 1,
					},
					inningsTotals: {
						runs: 245,
						overs: '65.0',
						wickets: 0,
						extras: 0,
					},
					fallOfWickets: [
						{ order: 1, name: 'David Warner', runs: 18 },
						{ order: 2, name: 'Usman Khawaja', runs: 55 },
						{ order: 3, name: 'Marnus Labuschagne', runs: 89 },
						{ order: 4, name: 'Steve Smith', runs: 112 },
						{ order: 5, name: 'Travis Head', runs: 158 },
						{ order: 6, name: 'Cameron Green', runs: 201 },
						{ order: 7, name: 'Alex Carey', runs: 230 },
						{ order: 8, name: 'Pat Cummins', runs: 240 },
						{ order: 9, name: 'Mitchell Starc', runs: 244 },
						{ order: 10, name: 'Nathan Lyon', runs: 245 },
					],
				},
				{
					declared: false,
					forfeited: false,
					battingTeam: 'England',
					description: 'England first innings',
					batters: [],
					bowlers: [],
					extras: {
						byes: 5,
						legByes: 4,
						noBalls: 1,
						penalties: 0,
						wides: 2,
					},
					inningsTotals: {
						runs: 361,
						overs: '89.5',
						wickets: 10,
						extras: 12,
					},
					fallOfWickets: [
						{ order: 1, name: 'Zak Crawley', runs: 28 },
						{ order: 2, name: 'Ben Duckett', runs: 74 },
						{ order: 3, name: 'Ollie Pope', runs: 132 },
						{ order: 4, name: 'Joe Root', runs: 189 },
						{ order: 5, name: 'Harry Brook', runs: 223 },
						{ order: 6, name: 'Ben Stokes', runs: 267 },
						{ order: 7, name: 'Jamie Smith', runs: 298 },
						{ order: 8, name: 'Stuart Broad', runs: 320 },
						{ order: 9, name: 'Ollie Robinson', runs: 344 },
						{ order: 10, name: 'James Anderson', runs: 361 },
					],
				},
				{
					declared: false,
					forfeited: false,
					battingTeam: 'Australia',
					description: 'Australia second innings',
					batters: [],
					bowlers: [],
					extras: {
						byes: 6,
						legByes: 5,
						noBalls: 2,
						penalties: 0,
						wides: 2,
					},
					inningsTotals: {
						runs: 258,
						overs: '78.1',
						wickets: 8,
						extras: 15,
					},
					fallOfWickets: [
						{ order: 1, name: 'David Warner', runs: 12 },
						{ order: 2, name: 'Usman Khawaja', runs: 41 },
						{ order: 3, name: 'Marnus Labuschagne', runs: 78 },
						{ order: 4, name: 'Steve Smith', runs: 105 },
						{ order: 5, name: 'Travis Head', runs: 144 },
						{ order: 6, name: 'Cameron Green', runs: 179 },
						{ order: 7, name: 'Alex Carey', runs: 220 },
						{ order: 8, name: 'Mitchell Starc', runs: 243 },
						{ order: 9, name: 'Nathan Lyon', runs: 258 },
						{ order: 10, name: 'Josh Hazlewood', runs: 258 },
					],
				},
				{
					declared: false,
					forfeited: false,
					battingTeam: 'England',
					description: 'England second innings',
					batters: [],
					bowlers: [],
					extras: {
						byes: 8,
						legByes: 6,
						noBalls: 3,
						penalties: 0,
						wides: 3,
					},
					inningsTotals: {
						runs: 364,
						overs: '92.5',
						wickets: 10,
						extras: 20,
					},
					fallOfWickets: [
						{ order: 1, name: 'Zak Crawley', runs: 35 },
						{ order: 2, name: 'Ben Duckett', runs: 88 },
						{ order: 3, name: 'Ollie Pope', runs: 143 },
						{ order: 4, name: 'Joe Root', runs: 210 },
						{ order: 5, name: 'Harry Brook', runs: 251 },
						{ order: 6, name: 'Ben Stokes', runs: 290 },
						{ order: 7, name: 'Jamie Smith', runs: 318 },
						{ order: 8, name: 'Stuart Broad', runs: 335 },
						{ order: 9, name: 'Ollie Robinson', runs: 352 },
						{ order: 10, name: 'James Anderson', runs: 364 },
					],
				},
			],
			result: {
				type: 'home-win',
				description: 'Australia win by an innings and 47 runs',
				winner: {
					type: 'runs',
					team: 'Australia',
					margin: 47,
				},
			},
		},
	},
} satisfies Story;

export const ResultWinByWickets = {
	args: {
		edition: 'UK',
		match: {
			...Fixture.args.match,
			kind: 'Result',
			innings: [
				{
					declared: false,
					forfeited: false,
					battingTeam: 'Australia',
					description: 'Australia first innings',
					batters: [],
					bowlers: [],
					extras: {
						byes: 3,
						legByes: 2,
						noBalls: 1,
						penalties: 0,
						wides: 0,
					},
					inningsTotals: {
						runs: 186,
						overs: '16.2',
						wickets: 3,
						extras: 6,
					},
					fallOfWickets: [
						{ order: 1, name: 'David Warner', runs: 22 },
						{ order: 2, name: 'Usman Khawaja', runs: 61 },
						{ order: 3, name: 'Marnus Labuschagne', runs: 95 },
					],
				},
				{
					declared: false,
					forfeited: false,
					battingTeam: 'England',
					description: 'England first innings',
					batters: [],
					bowlers: [],
					extras: {
						byes: 4,
						legByes: 2,
						noBalls: 1,
						penalties: 0,
						wides: 1,
					},
					inningsTotals: {
						runs: 182,
						overs: '20.0',
						wickets: 8,
						extras: 8,
					},
					fallOfWickets: [
						{ order: 1, name: 'Zak Crawley', runs: 9 },
						{ order: 2, name: 'Ben Duckett', runs: 31 },
						{ order: 3, name: 'Ollie Pope', runs: 58 },
						{ order: 4, name: 'Joe Root', runs: 84 },
						{ order: 5, name: 'Harry Brook', runs: 107 },
						{ order: 6, name: 'Ben Stokes', runs: 127 },
						{ order: 7, name: 'Jamie Smith', runs: 148 },
						{ order: 8, name: 'Stuart Broad', runs: 162 },
					],
				},
			],
			result: {
				type: 'home-win',
				winner: {
					type: 'wickets',
					team: 'Australia',
					margin: 2,
				},
			},
		},
	},
} satisfies Story;

export const ResultDrawn = {
	args: {
		edition: 'UK',
		match: {
			...Fixture.args.match,
			kind: 'Result',
			day: 4,
			innings: [
				{
					declared: false,
					forfeited: false,
					battingTeam: 'Australia',
					description: 'Australia first innings',
					batters: [],
					bowlers: [],
					extras: {
						byes: 5,
						legByes: 4,
						noBalls: 2,
						penalties: 0,
						wides: 1,
					},
					inningsTotals: {
						runs: 302,
						overs: '120.3',
						wickets: 10,
						extras: 12,
					},
					fallOfWickets: [
						{ order: 1, name: 'David Warner', runs: 14 },
						{ order: 2, name: 'Usman Khawaja', runs: 47 },
						{ order: 3, name: 'Marnus Labuschagne', runs: 83 },
						{ order: 4, name: 'Steve Smith', runs: 119 },
						{ order: 5, name: 'Travis Head', runs: 162 },
						{ order: 6, name: 'Cameron Green', runs: 198 },
						{ order: 7, name: 'Alex Carey', runs: 231 },
						{ order: 8, name: 'Mitchell Starc', runs: 256 },
						{ order: 9, name: 'Nathan Lyon', runs: 278 },
						{ order: 10, name: 'Josh Hazlewood', runs: 302 },
					],
				},
				{
					declared: false,
					forfeited: false,
					battingTeam: 'England',
					description: 'England first innings',
					batters: [],
					bowlers: [],
					extras: {
						byes: 3,
						legByes: 2,
						noBalls: 1,
						penalties: 0,
						wides: 2,
					},
					inningsTotals: {
						runs: 226,
						overs: '60.2',
						wickets: 10,
						extras: 8,
					},
					fallOfWickets: [
						{ order: 1, name: 'Zak Crawley', runs: 11 },
						{ order: 2, name: 'Ben Duckett', runs: 38 },
						{ order: 3, name: 'Ollie Pope', runs: 72 },
						{ order: 4, name: 'Joe Root', runs: 104 },
						{ order: 5, name: 'Harry Brook', runs: 133 },
						{ order: 6, name: 'Ben Stokes', runs: 158 },
						{ order: 7, name: 'Jamie Smith', runs: 178 },
						{ order: 8, name: 'Stuart Broad', runs: 196 },
						{ order: 9, name: 'Ollie Robinson', runs: 211 },
						{ order: 10, name: 'James Anderson', runs: 226 },
					],
				},
				{
					declared: true,
					forfeited: false,
					battingTeam: 'Australia',
					description: 'Australia second innings',
					batters: [],
					bowlers: [],
					extras: {
						byes: 4,
						legByes: 3,
						noBalls: 2,
						penalties: 0,
						wides: 1,
					},
					inningsTotals: {
						runs: 218,
						overs: '72.5',
						wickets: 5,
						extras: 10,
					},
					fallOfWickets: [
						{ order: 1, name: 'David Warner', runs: 30 },
						{ order: 2, name: 'Usman Khawaja', runs: 71 },
						{ order: 3, name: 'Marnus Labuschagne', runs: 110 },
						{ order: 4, name: 'Steve Smith', runs: 155 },
						{ order: 5, name: 'Travis Head', runs: 188 },
					],
				},
				{
					declared: false,
					forfeited: false,
					battingTeam: 'England',
					description: 'England second innings',
					batters: [],
					bowlers: [],
					extras: {
						byes: 6,
						legByes: 4,
						noBalls: 3,
						penalties: 0,
						wides: 2,
					},
					inningsTotals: {
						runs: 239,
						overs: '67.4',
						wickets: 7,
						extras: 15,
					},
					fallOfWickets: [
						{ order: 1, name: 'Zak Crawley', runs: 17 },
						{ order: 2, name: 'Ben Duckett', runs: 54 },
						{ order: 3, name: 'Ollie Pope', runs: 92 },
						{ order: 4, name: 'Joe Root', runs: 138 },
						{ order: 5, name: 'Harry Brook', runs: 171 },
						{ order: 6, name: 'Ben Stokes', runs: 203 },
						{ order: 7, name: 'Jamie Smith', runs: 225 },
					],
				},
			],
			result: {
				type: 'draw',
			},
		},
	},
} satisfies Story;
