name: DCR Issue
description: Describe the work that should be completed as part of this ticket
title: '[Task]: '
labels: ['Rota']
projects: ['guardian/88']
body:
  - type: markdown
    attributes:
      value: |
        The Dotcom team would like to help you with your proposed change. Please provide us with a brief and concise explanation for what you're looking to do. We will try to make the process easier with early feedback or advice.

        **When should an issue be created?**
        This is an optional process. If you own the code you're working on or feel confident about the change you're making then you should simply raise a PR as normal. We want developers and teams to feel empowered to make the choice about when to reach out.

        However, if your change affects core platform code or is introducing a new concept or pattern, or if you're just looking for more eyes, input, or simply want to track the work in an issue then this process is for you.

        **Who is responsible for closing this issue?**
        Once the issue is created, it is the responsibility of the _Dotcom team_ (@guardian/dotcom-platform) to provide feedback and help you get your change to the finish line.
  - type: textarea
    id: change-description
    attributes:
      label: Context
      description: Please describe the change and why it's needed
  - type: textarea
    id: priority
    attributes:
      label: Priority
      description: Please describe how urgent this change is
