stacks: [frontend]
regions: [eu-west-1]
deployments:
  frontend-cfn:
    type: cloud-formation
    parameters:
      templatePath: cloudformation.yml
      cloudFormationStackByTags: false
      cloudFormationStackName: rendering
      templateStageParameters:
        CODE:
          InstanceType: t4g.micro
        PROD:
          InstanceType: t4g.small
      amiParametersToTags:
        AMI:
          Recipe: dotcom-rendering-ARM
          BuiltBy: amigo
          AmigoStage: PROD
  rendering:
    type: autoscaling
    parameters:
      bucket: aws-frontend-artifacts
    dependencies:
      - frontend-static
      - frontend-cfn
  frontend-static:
    type: aws-s3
    parameters:
      bucket: aws-frontend-static
      cacheControl: public, max-age=315360000
      prefixStack: false
