import { literal, object, union } from 'valibot';

export const FEFormatSchema = object({
	design: union([
		literal('ArticleDesign'),
		literal('PictureDesign'),
		literal('GalleryDesign'),
		literal('AudioDesign'),
		literal('VideoDesign'),
		literal('CrosswordDesign'),
		literal('ReviewDesign'),
		literal('AnalysisDesign'),
		literal('CommentDesign'),
		literal('ExplainerDesign'),
		literal('LetterDesign'),
		literal('FeatureDesign'),
		literal('LiveBlogDesign'),
		literal('DeadBlogDesign'),
		literal('RecipeDesign'),
		literal('MatchReportDesign'),
		literal('InterviewDesign'),
		literal('EditorialDesign'),
		literal('QuizDesign'),
		literal('InteractiveDesign'),
		literal('PhotoEssayDesign'),
		literal('ObituaryDesign'),
		literal('FullPageInteractiveDesign'),
		literal('NewsletterSignupDesign'),
		literal('TimelineDesign'),
		literal('ProfileDesign'),
	]),
	theme: union([
		literal('NewsPillar'),
		literal('OpinionPillar'),
		literal('SportPillar'),
		literal('CulturePillar'),
		literal('LifestylePillar'),
		literal('SpecialReportTheme'),
		literal('Labs'),
		literal('SpecialReportAltTheme'),
	]),
	display: union([
		literal('StandardDisplay'),
		literal('ImmersiveDisplay'),
		literal('ShowcaseDisplay'),
		literal('NumberedListDisplay'),
	]),
});
