/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IContentStats {
    videos: number;
    images: number;
    text: number;
    tweets: number;
    pullquotes: number;
    audio: number;
    interactives: number;
    witness: number;
    richlinks: number;
    membership: number;
    embeds: number;
    comments: number;
    instagram: number;
    vines: number;
}
export interface IContentStatsArgs {
    videos: number;
    images: number;
    text: number;
    tweets: number;
    pullquotes: number;
    audio: number;
    interactives: number;
    witness: number;
    richlinks: number;
    membership: number;
    embeds: number;
    comments: number;
    instagram: number;
    vines: number;
}
export const ContentStatsCodec: thrift.IStructCodec<IContentStatsArgs, IContentStats> = {
    encode(args: IContentStatsArgs, output: thrift.TProtocol): void {
        const obj: any = {
            videos: args.videos,
            images: args.images,
            text: args.text,
            tweets: args.tweets,
            pullquotes: args.pullquotes,
            audio: args.audio,
            interactives: args.interactives,
            witness: args.witness,
            richlinks: args.richlinks,
            membership: args.membership,
            embeds: args.embeds,
            comments: args.comments,
            instagram: args.instagram,
            vines: args.vines
        };
        output.writeStructBegin("ContentStats");
        if (obj.videos != null) {
            output.writeFieldBegin("videos", thrift.TType.I32, 1);
            output.writeI32(obj.videos);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[videos] is unset!");
        }
        if (obj.images != null) {
            output.writeFieldBegin("images", thrift.TType.I32, 2);
            output.writeI32(obj.images);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[images] is unset!");
        }
        if (obj.text != null) {
            output.writeFieldBegin("text", thrift.TType.I32, 3);
            output.writeI32(obj.text);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[text] is unset!");
        }
        if (obj.tweets != null) {
            output.writeFieldBegin("tweets", thrift.TType.I32, 4);
            output.writeI32(obj.tweets);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[tweets] is unset!");
        }
        if (obj.pullquotes != null) {
            output.writeFieldBegin("pullquotes", thrift.TType.I32, 5);
            output.writeI32(obj.pullquotes);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[pullquotes] is unset!");
        }
        if (obj.audio != null) {
            output.writeFieldBegin("audio", thrift.TType.I32, 6);
            output.writeI32(obj.audio);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[audio] is unset!");
        }
        if (obj.interactives != null) {
            output.writeFieldBegin("interactives", thrift.TType.I32, 7);
            output.writeI32(obj.interactives);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[interactives] is unset!");
        }
        if (obj.witness != null) {
            output.writeFieldBegin("witness", thrift.TType.I32, 8);
            output.writeI32(obj.witness);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[witness] is unset!");
        }
        if (obj.richlinks != null) {
            output.writeFieldBegin("richlinks", thrift.TType.I32, 9);
            output.writeI32(obj.richlinks);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[richlinks] is unset!");
        }
        if (obj.membership != null) {
            output.writeFieldBegin("membership", thrift.TType.I32, 10);
            output.writeI32(obj.membership);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[membership] is unset!");
        }
        if (obj.embeds != null) {
            output.writeFieldBegin("embeds", thrift.TType.I32, 11);
            output.writeI32(obj.embeds);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[embeds] is unset!");
        }
        if (obj.comments != null) {
            output.writeFieldBegin("comments", thrift.TType.I32, 12);
            output.writeI32(obj.comments);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[comments] is unset!");
        }
        if (obj.instagram != null) {
            output.writeFieldBegin("instagram", thrift.TType.I32, 13);
            output.writeI32(obj.instagram);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[instagram] is unset!");
        }
        if (obj.vines != null) {
            output.writeFieldBegin("vines", thrift.TType.I32, 14);
            output.writeI32(obj.vines);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[vines] is unset!");
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IContentStats {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.I32) {
                        const value_1: number = input.readI32();
                        _args.videos = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.I32) {
                        const value_2: number = input.readI32();
                        _args.images = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.TType.I32) {
                        const value_3: number = input.readI32();
                        _args.text = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.TType.I32) {
                        const value_4: number = input.readI32();
                        _args.tweets = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.TType.I32) {
                        const value_5: number = input.readI32();
                        _args.pullquotes = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.TType.I32) {
                        const value_6: number = input.readI32();
                        _args.audio = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.TType.I32) {
                        const value_7: number = input.readI32();
                        _args.interactives = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.TType.I32) {
                        const value_8: number = input.readI32();
                        _args.witness = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.TType.I32) {
                        const value_9: number = input.readI32();
                        _args.richlinks = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.TType.I32) {
                        const value_10: number = input.readI32();
                        _args.membership = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.TType.I32) {
                        const value_11: number = input.readI32();
                        _args.embeds = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.TType.I32) {
                        const value_12: number = input.readI32();
                        _args.comments = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 13:
                    if (fieldType === thrift.TType.I32) {
                        const value_13: number = input.readI32();
                        _args.instagram = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 14:
                    if (fieldType === thrift.TType.I32) {
                        const value_14: number = input.readI32();
                        _args.vines = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.videos !== undefined && _args.images !== undefined && _args.text !== undefined && _args.tweets !== undefined && _args.pullquotes !== undefined && _args.audio !== undefined && _args.interactives !== undefined && _args.witness !== undefined && _args.richlinks !== undefined && _args.membership !== undefined && _args.embeds !== undefined && _args.comments !== undefined && _args.instagram !== undefined && _args.vines !== undefined) {
            return {
                videos: _args.videos,
                images: _args.images,
                text: _args.text,
                tweets: _args.tweets,
                pullquotes: _args.pullquotes,
                audio: _args.audio,
                interactives: _args.interactives,
                witness: _args.witness,
                richlinks: _args.richlinks,
                membership: _args.membership,
                embeds: _args.embeds,
                comments: _args.comments,
                instagram: _args.instagram,
                vines: _args.vines
            };
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read ContentStats from input");
        }
    }
};
export class ContentStats extends thrift.StructLike implements IContentStats {
    public videos: number;
    public images: number;
    public text: number;
    public tweets: number;
    public pullquotes: number;
    public audio: number;
    public interactives: number;
    public witness: number;
    public richlinks: number;
    public membership: number;
    public embeds: number;
    public comments: number;
    public instagram: number;
    public vines: number;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IContentStatsArgs) {
        super();
        if (args.videos != null) {
            const value_15: number = args.videos;
            this.videos = value_15;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[videos] is unset!");
        }
        if (args.images != null) {
            const value_16: number = args.images;
            this.images = value_16;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[images] is unset!");
        }
        if (args.text != null) {
            const value_17: number = args.text;
            this.text = value_17;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[text] is unset!");
        }
        if (args.tweets != null) {
            const value_18: number = args.tweets;
            this.tweets = value_18;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[tweets] is unset!");
        }
        if (args.pullquotes != null) {
            const value_19: number = args.pullquotes;
            this.pullquotes = value_19;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[pullquotes] is unset!");
        }
        if (args.audio != null) {
            const value_20: number = args.audio;
            this.audio = value_20;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[audio] is unset!");
        }
        if (args.interactives != null) {
            const value_21: number = args.interactives;
            this.interactives = value_21;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[interactives] is unset!");
        }
        if (args.witness != null) {
            const value_22: number = args.witness;
            this.witness = value_22;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[witness] is unset!");
        }
        if (args.richlinks != null) {
            const value_23: number = args.richlinks;
            this.richlinks = value_23;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[richlinks] is unset!");
        }
        if (args.membership != null) {
            const value_24: number = args.membership;
            this.membership = value_24;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[membership] is unset!");
        }
        if (args.embeds != null) {
            const value_25: number = args.embeds;
            this.embeds = value_25;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[embeds] is unset!");
        }
        if (args.comments != null) {
            const value_26: number = args.comments;
            this.comments = value_26;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[comments] is unset!");
        }
        if (args.instagram != null) {
            const value_27: number = args.instagram;
            this.instagram = value_27;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[instagram] is unset!");
        }
        if (args.vines != null) {
            const value_28: number = args.vines;
            this.vines = value_28;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[vines] is unset!");
        }
    }
    public static read(input: thrift.TProtocol): ContentStats {
        return new ContentStats(ContentStatsCodec.decode(input));
    }
    public static write(args: IContentStatsArgs, output: thrift.TProtocol): void {
        return ContentStatsCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return ContentStatsCodec.encode(this, output);
    }
}
