/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface ICrosswordCreator {
    name: string;
    webUrl: string;
}
export interface ICrosswordCreatorArgs {
    name: string;
    webUrl: string;
}
export const CrosswordCreatorCodec: thrift.IStructCodec<ICrosswordCreatorArgs, ICrosswordCreator> = {
    encode(args: ICrosswordCreatorArgs, output: thrift.TProtocol): void {
        const obj: any = {
            name: args.name,
            webUrl: args.webUrl
        };
        output.writeStructBegin("CrosswordCreator");
        if (obj.name != null) {
            output.writeFieldBegin("name", thrift.TType.STRING, 1);
            output.writeString(obj.name);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[name] is unset!");
        }
        if (obj.webUrl != null) {
            output.writeFieldBegin("webUrl", thrift.TType.STRING, 2);
            output.writeString(obj.webUrl);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[webUrl] is unset!");
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): ICrosswordCreator {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.name = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.webUrl = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.name !== undefined && _args.webUrl !== undefined) {
            return {
                name: _args.name,
                webUrl: _args.webUrl
            };
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read CrosswordCreator from input");
        }
    }
};
export class CrosswordCreator extends thrift.StructLike implements ICrosswordCreator {
    public name: string;
    public webUrl: string;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: ICrosswordCreatorArgs) {
        super();
        if (args.name != null) {
            const value_3: string = args.name;
            this.name = value_3;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[name] is unset!");
        }
        if (args.webUrl != null) {
            const value_4: string = args.webUrl;
            this.webUrl = value_4;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[webUrl] is unset!");
        }
    }
    public static read(input: thrift.TProtocol): CrosswordCreator {
        return new CrosswordCreator(CrosswordCreatorCodec.decode(input));
    }
    public static write(args: ICrosswordCreatorArgs, output: thrift.TProtocol): void {
        return CrosswordCreatorCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return CrosswordCreatorCodec.encode(this, output);
    }
}
