/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum Platform {
    YOUTUBE = 0,
    FACEBOOK = 1,
    DAILYMOTION = 2,
    MAINSTREAM = 3,
    URL = 4
}
