/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IPrice {
    currency: string;
    value: number;
}
export interface IPriceArgs {
    currency: string;
    value: number;
}
export const PriceCodec: thrift.IStructCodec<IPriceArgs, IPrice> = {
    encode(args: IPriceArgs, output: thrift.TProtocol): void {
        const obj: any = {
            currency: args.currency,
            value: args.value
        };
        output.writeStructBegin("Price");
        if (obj.currency != null) {
            output.writeFieldBegin("currency", thrift.TType.STRING, 1);
            output.writeString(obj.currency);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[currency] is unset!");
        }
        if (obj.value != null) {
            output.writeFieldBegin("value", thrift.TType.I32, 2);
            output.writeI32(obj.value);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[value] is unset!");
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IPrice {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.currency = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.I32) {
                        const value_2: number = input.readI32();
                        _args.value = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.currency !== undefined && _args.value !== undefined) {
            return {
                currency: _args.currency,
                value: _args.value
            };
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read Price from input");
        }
    }
};
export class Price extends thrift.StructLike implements IPrice {
    public currency: string;
    public value: number;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IPriceArgs) {
        super();
        if (args.currency != null) {
            const value_3: string = args.currency;
            this.currency = value_3;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[currency] is unset!");
        }
        if (args.value != null) {
            const value_4: number = args.value;
            this.value = value_4;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[value] is unset!");
        }
    }
    public static read(input: thrift.TProtocol): Price {
        return new Price(PriceCodec.decode(input));
    }
    public static write(args: IPriceArgs, output: thrift.TProtocol): void {
        return PriceCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return PriceCodec.encode(this, output);
    }
}
