/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IPullquoteElementFields {
    html?: string;
    attribution?: string;
    role?: string;
}
export interface IPullquoteElementFieldsArgs {
    html?: string;
    attribution?: string;
    role?: string;
}
export const PullquoteElementFieldsCodec: thrift.IStructCodec<IPullquoteElementFieldsArgs, IPullquoteElementFields> = {
    encode(args: IPullquoteElementFieldsArgs, output: thrift.TProtocol): void {
        const obj: any = {
            html: args.html,
            attribution: args.attribution,
            role: args.role
        };
        output.writeStructBegin("PullquoteElementFields");
        if (obj.html != null) {
            output.writeFieldBegin("html", thrift.TType.STRING, 1);
            output.writeString(obj.html);
            output.writeFieldEnd();
        }
        if (obj.attribution != null) {
            output.writeFieldBegin("attribution", thrift.TType.STRING, 2);
            output.writeString(obj.attribution);
            output.writeFieldEnd();
        }
        if (obj.role != null) {
            output.writeFieldBegin("role", thrift.TType.STRING, 3);
            output.writeString(obj.role);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IPullquoteElementFields {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.html = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.attribution = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.TType.STRING) {
                        const value_3: string = input.readString();
                        _args.role = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return {
            html: _args.html,
            attribution: _args.attribution,
            role: _args.role
        };
    }
};
export class PullquoteElementFields extends thrift.StructLike implements IPullquoteElementFields {
    public html?: string;
    public attribution?: string;
    public role?: string;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IPullquoteElementFieldsArgs = {}) {
        super();
        if (args.html != null) {
            const value_4: string = args.html;
            this.html = value_4;
        }
        if (args.attribution != null) {
            const value_5: string = args.attribution;
            this.attribution = value_5;
        }
        if (args.role != null) {
            const value_6: string = args.role;
            this.role = value_6;
        }
    }
    public static read(input: thrift.TProtocol): PullquoteElementFields {
        return new PullquoteElementFields(PullquoteElementFieldsCodec.decode(input));
    }
    public static write(args: IPullquoteElementFieldsArgs, output: thrift.TProtocol): void {
        return PullquoteElementFieldsCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return PullquoteElementFieldsCodec.encode(this, output);
    }
}
