/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum TagType {
    CONTRIBUTOR = 0,
    KEYWORD = 1,
    SERIES = 2,
    NEWSPAPER_BOOK_SECTION = 3,
    NEWSPAPER_BOOK = 4,
    BLOG = 5,
    TONE = 6,
    TYPE = 7,
    PUBLICATION = 8,
    TRACKING = 9,
    PAID_CONTENT = 10,
    CAMPAIGN = 11
}
