export const designTypes: Array<DesignType> = [
    'Article',
    'Immersive',
    'Media',
    'Review',
    'Analysis',
    'Comment',
    'Feature',
    'Live',
    'SpecialReport',
    'Recipe',
    'MatchReport',
    'Interview',
    'GuardianView',
    'GuardianLabs',
    'Quiz',
    'AdvertismentFeature',
];
