/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated using the gen-fixtures.ts script. Any edits
 * you make here will be lost.
 *
 * If the data in these fixtures is not what you expect then
 *
 * 1. Refresh the data using '$ node scrips/test-data/gen-fixtures.ts' or
 * 2. if the latest live data is not what you need, then consider editing
 *    gen-fixtures.ts directly.
 */

export const MatchReport: CAPIType = {
	slotMachineFlags: '',
	main:
		'<figure class="element element-image" data-media-id="cc1d3dc14ab9104587323ef12ac477004b369637"> <img src="https://media.guim.co.uk/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/1000.jpg" alt="André Ayew celebrates after giving Swansea the lead in their 2-0 home victory against Championship leaders Norwich." width="1000" height="600" class="gu-image" /> <figcaption> <span class="element-image__caption">André Ayew celebrates after giving Swansea the lead in their 2-0 home victory against Championship leaders Norwich.</span> <span class="element-image__credit">Photograph: Kieran McManus/BPI/Shutterstock</span> </figcaption> </figure>',
	subMetaSectionLinks: [
		{
			url: '/football/championship',
			title: 'Championship',
		},
	],
	commercialProperties: {
		UK: {
			adTargeting: [
				{
					name: 'edition',
					value: 'uk',
				},
				{
					name: 'url',
					value:
						'/football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top',
				},
				{
					name: 'k',
					value: [
						'norwichcity',
						'swansea',
						'championship',
						'sport',
						'football',
					],
				},
				{
					name: 'su',
					value: ['0'],
				},
				{
					name: 'ct',
					value: 'article',
				},
				{
					name: 'p',
					value: 'ng',
				},
				{
					name: 'sh',
					value: 'https://www.theguardian.com/p/gba7d',
				},
				{
					name: 'co',
					value: ['ben-fisher'],
				},
				{
					name: 'tn',
					value: ['matchreports'],
				},
			],
		},
		US: {
			adTargeting: [
				{
					name: 'url',
					value:
						'/football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top',
				},
				{
					name: 'k',
					value: [
						'norwichcity',
						'swansea',
						'championship',
						'sport',
						'football',
					],
				},
				{
					name: 'su',
					value: ['0'],
				},
				{
					name: 'ct',
					value: 'article',
				},
				{
					name: 'p',
					value: 'ng',
				},
				{
					name: 'sh',
					value: 'https://www.theguardian.com/p/gba7d',
				},
				{
					name: 'co',
					value: ['ben-fisher'],
				},
				{
					name: 'edition',
					value: 'us',
				},
				{
					name: 'tn',
					value: ['matchreports'],
				},
			],
		},
		AU: {
			adTargeting: [
				{
					name: 'url',
					value:
						'/football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top',
				},
				{
					name: 'k',
					value: [
						'norwichcity',
						'swansea',
						'championship',
						'sport',
						'football',
					],
				},
				{
					name: 'su',
					value: ['0'],
				},
				{
					name: 'ct',
					value: 'article',
				},
				{
					name: 'p',
					value: 'ng',
				},
				{
					name: 'sh',
					value: 'https://www.theguardian.com/p/gba7d',
				},
				{
					name: 'co',
					value: ['ben-fisher'],
				},
				{
					name: 'tn',
					value: ['matchreports'],
				},
				{
					name: 'edition',
					value: 'au',
				},
			],
		},
		INT: {
			adTargeting: [
				{
					name: 'url',
					value:
						'/football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top',
				},
				{
					name: 'k',
					value: [
						'norwichcity',
						'swansea',
						'championship',
						'sport',
						'football',
					],
				},
				{
					name: 'edition',
					value: 'int',
				},
				{
					name: 'su',
					value: ['0'],
				},
				{
					name: 'ct',
					value: 'article',
				},
				{
					name: 'p',
					value: 'ng',
				},
				{
					name: 'sh',
					value: 'https://www.theguardian.com/p/gba7d',
				},
				{
					name: 'co',
					value: ['ben-fisher'],
				},
				{
					name: 'tn',
					value: ['matchreports'],
				},
			],
		},
	},
	beaconURL: '//phar.gu-web.net',
	webPublicationSecondaryDateDisplay:
		'Last modified on Sat 6 Feb 2021 05.27 GMT',
	editionLongForm: 'UK edition',
	hasRelated: true,
	publication: 'The Guardian',
	trailText:
		'André Ayew and Conor Hourihane scored in the 2-0 home win against Norwich to lift Swansea to second, only two points behind the leaders',
	subMetaKeywordLinks: [
		{
			url: '/football/swansea',
			title: 'Swansea City',
		},
		{
			url: '/football/norwichcity',
			title: 'Norwich City',
		},
		{
			url: '/tone/matchreports',
			title: 'match reports',
		},
	],
	contentType: 'Article',
	nav: {
		currentUrl: '/football',
		pillars: [
			{
				title: 'News',
				url: '/',
				longTitle: 'Headlines',
				iconName: 'home',
				children: [
					{
						title: 'UK',
						url: '/uk-news',
						longTitle: 'UK news',
						children: [
							{
								title: 'UK politics',
								url: '/politics',
							},
							{
								title: 'Education',
								url: '/education',
								children: [
									{
										title: 'Schools',
										url: '/education/schools',
									},
									{
										title: 'Teachers',
										url: '/teacher-network',
									},
									{
										title: 'Universities',
										url: '/education/universities',
									},
									{
										title: 'Students',
										url: '/education/students',
									},
								],
							},
							{
								title: 'Media',
								url: '/media',
							},
							{
								title: 'Society',
								url: '/society',
							},
							{
								title: 'Law',
								url: '/law',
							},
							{
								title: 'Scotland',
								url: '/uk/scotland',
							},
							{
								title: 'Wales',
								url: '/uk/wales',
							},
							{
								title: 'Northern Ireland',
								url: '/uk/northernireland',
							},
						],
					},
					{
						title: 'World',
						url: '/world',
						longTitle: 'World news',
						children: [
							{
								title: 'Europe',
								url: '/world/europe-news',
							},
							{
								title: 'US',
								url: '/us-news',
								longTitle: 'US news',
							},
							{
								title: 'Americas',
								url: '/world/americas',
							},
							{
								title: 'Asia',
								url: '/world/asia',
							},
							{
								title: 'Australia',
								url: '/australia-news',
								longTitle: 'Australia news',
							},
							{
								title: 'Middle East',
								url: '/world/middleeast',
							},
							{
								title: 'Africa',
								url: '/world/africa',
							},
							{
								title: 'Inequality',
								url: '/inequality',
							},
							{
								title: 'Global development',
								url: '/global-development',
							},
						],
					},
					{
						title: 'Business',
						url: '/business',
						children: [
							{
								title: 'Economics',
								url: '/business/economics',
							},
							{
								title: 'Banking',
								url: '/business/banking',
							},
							{
								title: 'Money',
								url: '/money',
								children: [
									{
										title: 'Property',
										url: '/money/property',
									},
									{
										title: 'Pensions',
										url: '/money/pensions',
									},
									{
										title: 'Savings',
										url: '/money/savings',
									},
									{
										title: 'Borrowing',
										url: '/money/debt',
									},
									{
										title: 'Careers',
										url: '/money/work-and-careers',
									},
								],
							},
							{
								title: 'Markets',
								url: '/business/stock-markets',
							},
							{
								title: 'Project Syndicate',
								url:
									'/business/series/project-syndicate-economists',
							},
							{
								title: 'B2B',
								url: '/business-to-business',
							},
							{
								title: 'Retail',
								url: '/business/retail',
							},
						],
					},
					{
						title: 'Coronavirus',
						url: '/world/coronavirus-outbreak',
						longTitle: 'Coronavirus',
					},
					{
						title: 'Football',
						url: '/football',
						children: [
							{
								title: 'Live scores',
								url: '/football/live',
								longTitle: 'football/live',
							},
							{
								title: 'Tables',
								url: '/football/tables',
								longTitle: 'football/tables',
							},
							{
								title: 'Fixtures',
								url: '/football/fixtures',
								longTitle: 'football/fixtures',
							},
							{
								title: 'Results',
								url: '/football/results',
								longTitle: 'football/results',
							},
							{
								title: 'Competitions',
								url: '/football/competitions',
								longTitle: 'football/competitions',
							},
							{
								title: 'Clubs',
								url: '/football/teams',
								longTitle: 'football/teams',
							},
						],
					},
					{
						title: 'Environment',
						url: '/environment',
						children: [
							{
								title: 'Climate change',
								url: '/environment/climate-change',
							},
							{
								title: 'Wildlife',
								url: '/environment/wildlife',
							},
							{
								title: 'Energy',
								url: '/environment/energy',
							},
							{
								title: 'Pollution',
								url: '/environment/pollution',
							},
						],
					},
					{
						title: 'UK politics',
						url: '/politics',
					},
					{
						title: 'Education',
						url: '/education',
						children: [
							{
								title: 'Schools',
								url: '/education/schools',
							},
							{
								title: 'Teachers',
								url: '/teacher-network',
							},
							{
								title: 'Universities',
								url: '/education/universities',
							},
							{
								title: 'Students',
								url: '/education/students',
							},
						],
					},
					{
						title: 'Society',
						url: '/society',
					},
					{
						title: 'Science',
						url: '/science',
					},
					{
						title: 'Tech',
						url: '/technology',
					},
					{
						title: 'Global development',
						url: '/global-development',
					},
					{
						title: 'Obituaries',
						url: '/tone/obituaries',
					},
				],
			},
			{
				title: 'Opinion',
				url: '/commentisfree',
				longTitle: 'Opinion home',
				iconName: 'home',
				children: [
					{
						title: 'The Guardian view',
						url: '/profile/editorial',
					},
					{
						title: 'Columnists',
						url: '/index/contributors',
					},
					{
						title: 'Cartoons',
						url: '/cartoons/archive',
					},
					{
						title: 'Opinion videos',
						url: '/type/video+tone/comment',
					},
					{
						title: 'Letters',
						url: '/tone/letters',
					},
				],
			},
			{
				title: 'Sport',
				url: '/sport',
				longTitle: 'Sport home',
				iconName: 'home',
				children: [
					{
						title: 'Football',
						url: '/football',
						children: [
							{
								title: 'Live scores',
								url: '/football/live',
								longTitle: 'football/live',
							},
							{
								title: 'Tables',
								url: '/football/tables',
								longTitle: 'football/tables',
							},
							{
								title: 'Fixtures',
								url: '/football/fixtures',
								longTitle: 'football/fixtures',
							},
							{
								title: 'Results',
								url: '/football/results',
								longTitle: 'football/results',
							},
							{
								title: 'Competitions',
								url: '/football/competitions',
								longTitle: 'football/competitions',
							},
							{
								title: 'Clubs',
								url: '/football/teams',
								longTitle: 'football/teams',
							},
						],
					},
					{
						title: 'Cricket',
						url: '/sport/cricket',
					},
					{
						title: 'Rugby union',
						url: '/sport/rugby-union',
					},
					{
						title: 'Tennis',
						url: '/sport/tennis',
					},
					{
						title: 'Cycling',
						url: '/sport/cycling',
					},
					{
						title: 'F1',
						url: '/sport/formulaone',
					},
					{
						title: 'Golf',
						url: '/sport/golf',
					},
					{
						title: 'Boxing',
						url: '/sport/boxing',
					},
					{
						title: 'Rugby league',
						url: '/sport/rugbyleague',
					},
					{
						title: 'Racing',
						url: '/sport/horse-racing',
					},
					{
						title: 'US sports',
						url: '/sport/us-sport',
					},
				],
			},
			{
				title: 'Culture',
				url: '/culture',
				longTitle: 'Culture home',
				iconName: 'home',
				children: [
					{
						title: 'Film',
						url: '/film',
					},
					{
						title: 'Music',
						url: '/music',
					},
					{
						title: 'TV & radio',
						url: '/tv-and-radio',
					},
					{
						title: 'Books',
						url: '/books',
					},
					{
						title: 'Art & design',
						url: '/artanddesign',
					},
					{
						title: 'Stage',
						url: '/stage',
					},
					{
						title: 'Games',
						url: '/games',
					},
					{
						title: 'Classical',
						url: '/music/classicalmusicandopera',
					},
				],
			},
			{
				title: 'Lifestyle',
				url: '/lifeandstyle',
				longTitle: 'Lifestyle home',
				iconName: 'home',
				children: [
					{
						title: 'Fashion',
						url: '/fashion',
					},
					{
						title: 'Food',
						url: '/food',
					},
					{
						title: 'Recipes',
						url: '/tone/recipes',
					},
					{
						title: 'Travel',
						url: '/travel',
						children: [
							{
								title: 'UK',
								url: '/travel/uk',
							},
							{
								title: 'Europe',
								url: '/travel/europe',
							},
							{
								title: 'US',
								url: '/travel/usa',
							},
						],
					},
					{
						title: 'Health & fitness',
						url: '/lifeandstyle/health-and-wellbeing',
					},
					{
						title: 'Women',
						url: '/lifeandstyle/women',
					},
					{
						title: 'Men',
						url: '/lifeandstyle/men',
					},
					{
						title: 'Love & sex',
						url: '/lifeandstyle/love-and-sex',
					},
					{
						title: 'Beauty',
						url: '/fashion/beauty',
					},
					{
						title: 'Home & garden',
						url: '/lifeandstyle/home-and-garden',
					},
					{
						title: 'Money',
						url: '/money',
						children: [
							{
								title: 'Property',
								url: '/money/property',
							},
							{
								title: 'Pensions',
								url: '/money/pensions',
							},
							{
								title: 'Savings',
								url: '/money/savings',
							},
							{
								title: 'Borrowing',
								url: '/money/debt',
							},
							{
								title: 'Careers',
								url: '/money/work-and-careers',
							},
						],
					},
					{
						title: 'Cars',
						url: '/technology/motoring',
					},
				],
			},
		],
		otherLinks: [
			{
				title: 'The Guardian app',
				url:
					'https://www.theguardian.com/mobile/2014/may/29/the-guardian-for-mobile-and-tablet',
			},
			{
				title: 'Video',
				url: '/video',
			},
			{
				title: 'Podcasts',
				url: '/podcasts',
			},
			{
				title: 'Pictures',
				url: '/inpictures',
			},
			{
				title: 'Newsletters',
				url: '/email-newsletters',
			},
			{
				title: "Today's paper",
				url: '/theguardian',
				children: [
					{
						title: 'Obituaries',
						url: '/tone/obituaries',
					},
					{
						title: 'G2',
						url: '/theguardian/g2',
					},
					{
						title: 'Weekend',
						url: '/theguardian/weekend',
					},
					{
						title: 'The Guide',
						url: '/theguardian/theguide',
					},
					{
						title: 'Saturday review',
						url: '/theguardian/guardianreview',
					},
				],
			},
			{
				title: 'Inside the Guardian',
				url: 'https://www.theguardian.com/membership',
			},
			{
				title: 'The Observer',
				url: '/observer',
				children: [
					{
						title: 'Comment',
						url: '/theobserver/news/comment',
					},
					{
						title: 'The New Review',
						url: '/theobserver/new-review',
					},
					{
						title: 'Observer Magazine',
						url: '/theobserver/magazine',
					},
					{
						title: 'Observer Food Monthly',
						url: '/theobserver/foodmonthly',
					},
				],
			},
			{
				title: 'Guardian Weekly',
				url:
					'https://www.theguardian.com/weekly?INTCMP=gdnwb_mawns_editorial_gweekly_GW_TopNav_UK',
			},
			{
				title: 'Crosswords',
				url: '/crosswords',
				children: [
					{
						title: 'Blog',
						url: '/crosswords/crossword-blog',
					},
					{
						title: 'Quick',
						url: '/crosswords/series/quick',
					},
					{
						title: 'Cryptic',
						url: '/crosswords/series/cryptic',
					},
					{
						title: 'Prize',
						url: '/crosswords/series/prize',
					},
					{
						title: 'Weekend',
						url: '/crosswords/series/weekend-crossword',
					},
					{
						title: 'Quiptic',
						url: '/crosswords/series/quiptic',
					},
					{
						title: 'Genius',
						url: '/crosswords/series/genius',
					},
					{
						title: 'Speedy',
						url: '/crosswords/series/speedy',
					},
					{
						title: 'Everyman',
						url: '/crosswords/series/everyman',
					},
					{
						title: 'Azed',
						url: '/crosswords/series/azed',
					},
				],
			},
		],
		brandExtensions: [
			{
				title: 'Search jobs',
				url:
					'https://jobs.theguardian.com?INTCMP=jobs_uk_web_newheader_dropdown',
			},
			{
				title: 'Hire with Guardian Jobs',
				url:
					'https://recruiters.theguardian.com/?utm_source=gdnwb&utm_medium=navbar&utm_campaign=Guardian_Navbar_Recruiters&CMP_TU=trdmkt&CMP_BUNIT=jobs',
			},
			{
				title: 'Holidays',
				url:
					'https://holidays.theguardian.com?INTCMP=holidays_uk_web_newheader',
			},
			{
				title: 'Live events',
				url:
					'https://membership.theguardian.com/events?INTCMP=live_uk_header_dropdown',
			},
			{
				title: 'Masterclasses',
				url: '/guardian-masterclasses',
			},
			{
				title: 'Digital Archive',
				url: 'https://theguardian.newspapers.com',
			},
			{
				title: 'Guardian Print Shop',
				url: '/artanddesign/series/gnm-print-sales',
			},
			{
				title: 'Patrons',
				url: 'https://patrons.theguardian.com/?INTCMP=header_patrons',
			},
			{
				title: 'Guardian Puzzles app',
				url: 'https://puzzles.theguardian.com/download',
			},
		],
		currentNavLinkTitle: 'Football',
		currentPillarTitle: 'Sport',
		subNavSections: {
			parent: {
				title: 'Football',
				url: '/football',
				children: [
					{
						title: 'Live scores',
						url: '/football/live',
						longTitle: 'football/live',
					},
					{
						title: 'Tables',
						url: '/football/tables',
						longTitle: 'football/tables',
					},
					{
						title: 'Fixtures',
						url: '/football/fixtures',
						longTitle: 'football/fixtures',
					},
					{
						title: 'Results',
						url: '/football/results',
						longTitle: 'football/results',
					},
					{
						title: 'Competitions',
						url: '/football/competitions',
						longTitle: 'football/competitions',
					},
					{
						title: 'Clubs',
						url: '/football/teams',
						longTitle: 'football/teams',
					},
				],
			},
			links: [
				{
					title: 'Live scores',
					url: '/football/live',
					longTitle: 'football/live',
				},
				{
					title: 'Tables',
					url: '/football/tables',
					longTitle: 'football/tables',
				},
				{
					title: 'Fixtures',
					url: '/football/fixtures',
					longTitle: 'football/fixtures',
				},
				{
					title: 'Results',
					url: '/football/results',
					longTitle: 'football/results',
				},
				{
					title: 'Competitions',
					url: '/football/competitions',
					longTitle: 'football/competitions',
				},
				{
					title: 'Clubs',
					url: '/football/teams',
					longTitle: 'football/teams',
				},
			],
		},
		readerRevenueLinks: {
			header: {
				contribute:
					'https://support.theguardian.com/contribute?INTCMP=header_support_contribute&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_HEADER%22,%22componentId%22:%22header_support_contribute%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				subscribe:
					'https://support.theguardian.com/subscribe?INTCMP=header_support_subscribe&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_HEADER%22,%22componentId%22:%22header_support_subscribe%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				support:
					'https://support.theguardian.com?INTCMP=header_support&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_HEADER%22,%22componentId%22:%22header_support%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				gifting:
					'https://support.theguardian.com/subscribe?INTCMP=header_support_gifting&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_HEADER%22,%22componentId%22:%22header_support_gifting%22,%22source%22:%22GUARDIAN_WEB%22%7D',
			},
			footer: {
				contribute:
					'https://support.theguardian.com/contribute?INTCMP=footer_support_contribute&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_FOOTER%22,%22componentId%22:%22footer_support_contribute%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				subscribe:
					'https://support.theguardian.com/subscribe?INTCMP=footer_support_subscribe&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_FOOTER%22,%22componentId%22:%22footer_support_subscribe%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				support:
					'https://support.theguardian.com?INTCMP=footer_support&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_FOOTER%22,%22componentId%22:%22footer_support%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				gifting:
					'https://support.theguardian.com/subscribe?INTCMP=footer_support_gifting&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_FOOTER%22,%22componentId%22:%22footer_support_gifting%22,%22source%22:%22GUARDIAN_WEB%22%7D',
			},
			sideMenu: {
				contribute:
					'https://support.theguardian.com/contribute?INTCMP=side_menu_support_contribute&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_HEADER%22,%22componentId%22:%22side_menu_support_contribute%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				subscribe:
					'https://support.theguardian.com/subscribe?INTCMP=side_menu_support_subscribe&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_HEADER%22,%22componentId%22:%22side_menu_support_subscribe%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				support:
					'https://support.theguardian.com?INTCMP=side_menu_support&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_HEADER%22,%22componentId%22:%22side_menu_support%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				gifting:
					'https://support.theguardian.com/subscribe?INTCMP=side_menu_support_gifting&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_HEADER%22,%22componentId%22:%22side_menu_support_gifting%22,%22source%22:%22GUARDIAN_WEB%22%7D',
			},
			ampHeader: {
				contribute:
					'https://support.theguardian.com/contribute?INTCMP=header_support_contribute&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_HEADER%22,%22componentId%22:%22header_support_contribute%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				subscribe:
					'https://support.theguardian.com/subscribe?INTCMP=header_support_subscribe&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_HEADER%22,%22componentId%22:%22header_support_subscribe%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				support:
					'https://support.theguardian.com?INTCMP=amp_header_support&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_HEADER%22,%22componentId%22:%22amp_header_support%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				gifting:
					'https://support.theguardian.com/subscribe?INTCMP=header_support_gifting&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_HEADER%22,%22componentId%22:%22header_support_gifting%22,%22source%22:%22GUARDIAN_WEB%22%7D',
			},
			ampFooter: {
				contribute:
					'https://support.theguardian.com/contribute?INTCMP=amp_footer_support_contribute&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_FOOTER%22,%22componentId%22:%22amp_footer_support_contribute%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				subscribe:
					'https://support.theguardian.com/subscribe?INTCMP=amp_footer_support_subscribe&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_FOOTER%22,%22componentId%22:%22amp_footer_support_subscribe%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				support:
					'https://support.theguardian.com?INTCMP=footer_support&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_FOOTER%22,%22componentId%22:%22footer_support%22,%22source%22:%22GUARDIAN_WEB%22%7D',
				gifting:
					'https://support.theguardian.com/subscribe?INTCMP=amp_footer_support_gifting&acquisitionData=%7B%22componentType%22:%22ACQUISITIONS_FOOTER%22,%22componentId%22:%22amp_footer_support_gifting%22,%22source%22:%22GUARDIAN_WEB%22%7D',
			},
		},
	},
	author: {
		byline: 'Ben Fisher at the Liberty Stadium',
	},
	designType: 'MatchReport',
	editionId: 'UK',
	format: {
		design: 'MatchReportDesign',
		theme: 'SportPillar',
		display: 'StandardDisplay',
	},
	standfirst: '',
	openGraphData: {
		'og:url':
			'http://www.theguardian.com/football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top',
		'article:author': 'https://www.theguardian.com/profile/ben-fisher',
		'og:image:height': '720',
		'og:description':
			'André Ayew and Conor Hourihane scored in the 2-0 home win against Norwich to lift Swansea to second, only two points behind the leaders',
		'og:image:width': '1200',
		'og:image':
			'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=b8519d3db69446bfb443279cd19db7b5',
		'al:ios:url':
			'gnmguardian://football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top?contenttype=Article&source=applinks',
		'article:publisher': 'https://www.facebook.com/theguardian',
		'og:type': 'article',
		'al:ios:app_store_id': '409128287',
		'article:section': 'Football',
		'article:published_time': '2021-02-05T22:16:43.000Z',
		'og:title':
			'André Ayew sparks Swansea victory over Norwich to close gap at top',
		'fb:app_id': '180444840287',
		'article:tag': 'Championship,Swansea City,Norwich City,Football,Sport',
		'al:ios:app_name': 'The Guardian',
		'og:site_name': 'the Guardian',
		'article:modified_time': '2021-02-06T05:27:20.000Z',
	},
	sectionUrl: 'football/championship',
	pageId:
		'football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top',
	version: 3,
	tags: [
		{
			id: 'football/championship',
			type: 'Keyword',
			title: 'Championship',
		},
		{
			id: 'football/swansea',
			type: 'Keyword',
			title: 'Swansea City',
		},
		{
			id: 'football/norwichcity',
			type: 'Keyword',
			title: 'Norwich City',
		},
		{
			id: 'football/football',
			type: 'Keyword',
			title: 'Football',
		},
		{
			id: 'sport/sport',
			type: 'Keyword',
			title: 'Sport',
		},
		{
			id: 'type/article',
			type: 'Type',
			title: 'Article',
		},
		{
			id: 'tone/matchreports',
			type: 'Tone',
			title: 'Match reports',
		},
		{
			id: 'profile/ben-fisher',
			type: 'Contributor',
			title: 'Ben Fisher',
			bylineImageUrl:
				'https://i.guim.co.uk/img/uploads/2017/11/06/Ben_Fisher,_L.png?width=300&quality=85&auto=format&fit=max&s=c7012d74bff5e3b4952656e3a8ceb105',
		},
		{
			id: 'publication/theguardian',
			type: 'Publication',
			title: 'The Guardian',
		},
		{
			id: 'theguardian/sport',
			type: 'NewspaperBook',
			title: 'Sport',
		},
		{
			id: 'theguardian/sport/news',
			type: 'NewspaperBookSection',
			title: 'News & features',
		},
		{
			id: 'tracking/commissioningdesk/uk-sport',
			type: 'Tracking',
			title: 'UK Sport',
		},
	],
	pillar: 'sport',
	webURL:
		'https://www.theguardian.com/football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top',
	showBottomSocialButtons: true,
	isImmersive: false,
	sectionLabel: 'Championship',
	shouldHideReaderRevenue: false,
	isAdFreeUser: false,
	pageFooter: {
		footerLinks: [
			[
				{
					text: 'About us',
					url: '/about',
					dataLinkName: 'uk : footer : about us',
					extraClasses: '',
				},
				{
					text: 'Contact us',
					url: '/help/contact-us',
					dataLinkName: 'uk : footer : contact us',
					extraClasses: '',
				},
				{
					text: 'Complaints & corrections',
					url: '/info/complaints-and-corrections',
					dataLinkName: 'complaints',
					extraClasses: '',
				},
				{
					text: 'SecureDrop',
					url: 'https://www.theguardian.com/securedrop',
					dataLinkName: 'securedrop',
					extraClasses: '',
				},
				{
					text: 'Work for us',
					url: 'https://workforus.theguardian.com',
					dataLinkName: 'uk : footer : work for us',
					extraClasses: '',
				},
				{
					text: 'Privacy policy',
					url: '/info/privacy',
					dataLinkName: 'privacy',
					extraClasses: '',
				},
				{
					text: 'Cookie policy',
					url: '/info/cookies',
					dataLinkName: 'cookie',
					extraClasses: '',
				},
				{
					text: 'Terms & conditions',
					url: '/help/terms-of-service',
					dataLinkName: 'terms',
					extraClasses: '',
				},
				{
					text: 'Help',
					url: '/help',
					dataLinkName: 'uk : footer : tech feedback',
					extraClasses: 'js-tech-feedback-report',
				},
			],
			[
				{
					text: 'All topics',
					url: '/index/subjects/a',
					dataLinkName: 'uk : footer : all topics',
					extraClasses: '',
				},
				{
					text: 'All writers',
					url: '/index/contributors',
					dataLinkName: 'uk : footer : all contributors',
					extraClasses: '',
				},
				{
					text: 'Modern Slavery Act',
					url:
						'/info/2016/jul/27/modern-slavery-and-our-supply-chains?INTCMP=NGW_FOOTER_UK_GU_MODERN_SLAVERY_ACT',
					dataLinkName: 'uk : footer : modern slavery act statement',
					extraClasses: '',
				},
				{
					text: 'Digital newspaper archive',
					url: 'https://theguardian.newspapers.com',
					dataLinkName: 'digital newspaper archive',
					extraClasses: '',
				},
				{
					text: 'Facebook',
					url: 'https://www.facebook.com/theguardian',
					dataLinkName: 'uk : footer : facebook',
					extraClasses: '',
				},
				{
					text: 'YouTube',
					url: 'https://www.youtube.com/user/TheGuardian',
					dataLinkName: 'uk : footer : youtube',
					extraClasses: '',
				},
				{
					text: 'Instagram',
					url: 'https://www.instagram.com/guardian',
					dataLinkName: 'uk : footer : instagram',
					extraClasses: '',
				},
				{
					text: 'LinkedIn',
					url: 'https://www.linkedin.com/company/theguardian',
					dataLinkName: 'uk : footer : linkedin',
					extraClasses: '',
				},
				{
					text: 'Twitter',
					url: 'https://twitter.com/guardian',
					dataLinkName: 'uk: footer : twitter',
					extraClasses: '',
				},
				{
					text: 'Newsletters',
					url:
						'/email-newsletters?INTCMP=DOTCOM_FOOTER_NEWSLETTER_UK',
					dataLinkName: 'uk : footer : newsletters',
					extraClasses: '',
				},
			],
			[
				{
					text: 'Advertise with us',
					url: 'https://advertising.theguardian.com',
					dataLinkName: 'uk : footer : advertise with us',
					extraClasses: '',
				},
				{
					text: 'Guardian Labs',
					url: '/guardian-labs',
					dataLinkName: 'uk : footer : guardian labs',
					extraClasses: '',
				},
				{
					text: 'Search jobs',
					url:
						'https://jobs.theguardian.com?INTCMP=NGW_FOOTER_UK_GU_JOBS',
					dataLinkName: 'uk : footer : jobs',
					extraClasses: '',
				},
				{
					text: 'Patrons',
					url:
						'https://patrons.theguardian.com?INTCMP=footer_patrons',
					dataLinkName: 'uk : footer : patrons',
					extraClasses: '',
				},
			],
		],
	},
	twitterData: {
		'twitter:app:id:iphone': '409128287',
		'twitter:app:name:googleplay': 'The Guardian',
		'twitter:app:name:ipad': 'The Guardian',
		'twitter:image':
			'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&s=63f5549570734f5edf36122ad2d62b30',
		'twitter:site': '@guardian',
		'twitter:app:url:ipad':
			'gnmguardian://football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top?contenttype=Article&source=twitter',
		'twitter:card': 'summary_large_image',
		'twitter:app:name:iphone': 'The Guardian',
		'twitter:app:id:ipad': '409128287',
		'twitter:app:id:googleplay': 'com.guardian',
		'twitter:app:url:googleplay':
			'guardian://www.theguardian.com/football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top',
		'twitter:app:url:iphone':
			'gnmguardian://football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top?contenttype=Article&source=twitter',
	},
	sectionName: 'football',
	pageType: {
		hasShowcaseMainElement: false,
		isFront: false,
		isLiveblog: false,
		isMinuteArticle: false,
		isPaidContent: false,
		isPreview: false,
		isSensitive: false,
	},
	hasStoryPackage: false,
	contributionsServiceUrl: 'https://contributions.guardianapis.com',
	matchUrl:
		'https://api.nextgen.guardianapps.co.uk/football/api/match-nav/2021/02/05/65/14.json?dcr=true&page=football%2F2021%2Ffeb%2F05%2Fandre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top',
	headline:
		'André Ayew sparks Swansea victory over Norwich to close gap at top',
	guardianBaseURL: 'https://www.theguardian.com',
	mainMediaElements: [
		{
			elementId: '47f2382c-adf3-4a41-90c4-4cd2629eecc6',
			role: 'inline',
			data: {
				alt:
					'André Ayew celebrates after giving Swansea the lead in their 2-0 home victory against Championship leaders Norwich.',
				caption:
					'André Ayew celebrates after giving Swansea the lead in their 2-0 home victory against Championship leaders Norwich.',
				credit: 'Photograph: Kieran McManus/BPI/Shutterstock',
			},
			imageSources: [
				{
					weighting: 'inline',
					srcSet: [
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=620&quality=85&auto=format&fit=max&s=2e852cd56aed3ab41675e2dbb380a93c',
							width: 620,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=620&quality=45&auto=format&fit=max&dpr=2&s=208554c4cb446786a0856ec41f97b550',
							width: 1240,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=605&quality=85&auto=format&fit=max&s=7cf31e91b66cdff430159385c573848c',
							width: 605,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=605&quality=45&auto=format&fit=max&dpr=2&s=b3f503e873cba7ab501ca0bcc90ba063',
							width: 1210,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=445&quality=85&auto=format&fit=max&s=226d9fc8084be99e0dfe08f66421fcba',
							width: 445,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=445&quality=45&auto=format&fit=max&dpr=2&s=33fa0d7a99e09629baad6038c09d29a2',
							width: 890,
						},
					],
				},
				{
					weighting: 'thumbnail',
					srcSet: [
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=140&quality=85&auto=format&fit=max&s=ca1fc952b0b5bfcbfb7a8666c110e597',
							width: 140,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=140&quality=45&auto=format&fit=max&dpr=2&s=9490e2983dc38e7abcc0819d07358e2d',
							width: 280,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=120&quality=85&auto=format&fit=max&s=fc7bf55b34904547630abb290e07ba2b',
							width: 120,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=120&quality=45&auto=format&fit=max&dpr=2&s=7f7b2be69723c4c6571336362b432805',
							width: 240,
						},
					],
				},
				{
					weighting: 'supporting',
					srcSet: [
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=380&quality=85&auto=format&fit=max&s=0b6cd1334b62c2cdf3a69e7b8fb5682e',
							width: 380,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=380&quality=45&auto=format&fit=max&dpr=2&s=3ceac779c69416232712bf4c8e99032f',
							width: 760,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=300&quality=85&auto=format&fit=max&s=ebcc0889e3b990c755a1f2674f55b139',
							width: 300,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=300&quality=45&auto=format&fit=max&dpr=2&s=3acf7faad2c14d8fb8ce977dc8d74399',
							width: 600,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=620&quality=85&auto=format&fit=max&s=2e852cd56aed3ab41675e2dbb380a93c',
							width: 620,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=620&quality=45&auto=format&fit=max&dpr=2&s=208554c4cb446786a0856ec41f97b550',
							width: 1240,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=605&quality=85&auto=format&fit=max&s=7cf31e91b66cdff430159385c573848c',
							width: 605,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=605&quality=45&auto=format&fit=max&dpr=2&s=b3f503e873cba7ab501ca0bcc90ba063',
							width: 1210,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=445&quality=85&auto=format&fit=max&s=226d9fc8084be99e0dfe08f66421fcba',
							width: 445,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=445&quality=45&auto=format&fit=max&dpr=2&s=33fa0d7a99e09629baad6038c09d29a2',
							width: 890,
						},
					],
				},
				{
					weighting: 'showcase',
					srcSet: [
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1020&quality=85&auto=format&fit=max&s=218bd7173095566fc62bc0e5b6f19f31',
							width: 1020,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1020&quality=45&auto=format&fit=max&dpr=2&s=921d1bac4fa4864c5834c185c1440596',
							width: 2040,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=940&quality=85&auto=format&fit=max&s=33cee4387567d8dc5989a2cb74744605',
							width: 940,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=940&quality=45&auto=format&fit=max&dpr=2&s=efe8f8ce7874db475bad461e7e6c37a2',
							width: 1880,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=700&quality=85&auto=format&fit=max&s=c26150091859708116bb6f3b1d8e6fd7',
							width: 700,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=700&quality=45&auto=format&fit=max&dpr=2&s=e5badc76e3ddac60f7166895d09d444e',
							width: 1400,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=700&quality=85&auto=format&fit=max&s=c26150091859708116bb6f3b1d8e6fd7',
							width: 700,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=700&quality=45&auto=format&fit=max&dpr=2&s=e5badc76e3ddac60f7166895d09d444e',
							width: 1400,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=660&quality=85&auto=format&fit=max&s=8e9b081837d4367f83a7633713e45eee',
							width: 660,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=660&quality=45&auto=format&fit=max&dpr=2&s=2dd8e33f8868179ff7bc099e4170f224',
							width: 1320,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=645&quality=85&auto=format&fit=max&s=3137a1577d4433cdf7b6e95fd8d4cf78',
							width: 645,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=645&quality=45&auto=format&fit=max&dpr=2&s=09f4336af469ce67ced5fe9df7c83e5e',
							width: 1290,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=465&quality=85&auto=format&fit=max&s=271e6711f51b1c0055793baf2749bd32',
							width: 465,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=465&quality=45&auto=format&fit=max&dpr=2&s=d7df199c9bd479a283c3a7afb80736e8',
							width: 930,
						},
					],
				},
				{
					weighting: 'halfwidth',
					srcSet: [
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=620&quality=85&auto=format&fit=max&s=2e852cd56aed3ab41675e2dbb380a93c',
							width: 620,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=620&quality=45&auto=format&fit=max&dpr=2&s=208554c4cb446786a0856ec41f97b550',
							width: 1240,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=605&quality=85&auto=format&fit=max&s=7cf31e91b66cdff430159385c573848c',
							width: 605,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=605&quality=45&auto=format&fit=max&dpr=2&s=b3f503e873cba7ab501ca0bcc90ba063',
							width: 1210,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=445&quality=85&auto=format&fit=max&s=226d9fc8084be99e0dfe08f66421fcba',
							width: 445,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=445&quality=45&auto=format&fit=max&dpr=2&s=33fa0d7a99e09629baad6038c09d29a2',
							width: 890,
						},
					],
				},
				{
					weighting: 'immersive',
					srcSet: [
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1300&quality=85&auto=format&fit=max&s=da89361749c2db884b396202fe281df2',
							width: 1300,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1300&quality=45&auto=format&fit=max&dpr=2&s=7ee884b9c6840d7993cdff8bb5b608e2',
							width: 2600,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1140&quality=85&auto=format&fit=max&s=73dda51a11db9bc1df0f918c2d0222ef',
							width: 1140,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1140&quality=45&auto=format&fit=max&dpr=2&s=e54589b2000f6314ab8083e69b199edc',
							width: 2280,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1125&quality=85&auto=format&fit=max&s=b37a0e995403ea1f5e2b9c7a3cd4ec2a',
							width: 1125,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1125&quality=45&auto=format&fit=max&dpr=2&s=d87c09c55375ad9095089dca71189b38',
							width: 2250,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=965&quality=85&auto=format&fit=max&s=ef553179832fe351026879cd5cca4017',
							width: 965,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=965&quality=45&auto=format&fit=max&dpr=2&s=f7992d9e3a74bca6f832ef8d7156bdf4',
							width: 1930,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=725&quality=85&auto=format&fit=max&s=474e255381529f0047dff2dd11389d1b',
							width: 725,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=725&quality=45&auto=format&fit=max&dpr=2&s=28c4b267f9038263223f14307704c4fa',
							width: 1450,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=645&quality=85&auto=format&fit=max&s=3137a1577d4433cdf7b6e95fd8d4cf78',
							width: 645,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=645&quality=45&auto=format&fit=max&dpr=2&s=09f4336af469ce67ced5fe9df7c83e5e',
							width: 1290,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=465&quality=85&auto=format&fit=max&s=271e6711f51b1c0055793baf2749bd32',
							width: 465,
						},
						{
							src:
								'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=465&quality=45&auto=format&fit=max&dpr=2&s=d7df199c9bd479a283c3a7afb80736e8',
							width: 930,
						},
					],
				},
			],
			_type: 'model.dotcomrendering.pageElements.ImageBlockElement',
			media: {
				allImages: [
					{
						index: 0,
						fields: {
							height: '600',
							width: '1000',
						},
						mediaType: 'Image',
						mimeType: 'image/jpeg',
						url:
							'https://media.guim.co.uk/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/1000.jpg',
					},
					{
						index: 1,
						fields: {
							height: '300',
							width: '500',
						},
						mediaType: 'Image',
						mimeType: 'image/jpeg',
						url:
							'https://media.guim.co.uk/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/500.jpg',
					},
					{
						index: 2,
						fields: {
							height: '84',
							width: '140',
						},
						mediaType: 'Image',
						mimeType: 'image/jpeg',
						url:
							'https://media.guim.co.uk/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/140.jpg',
					},
					{
						index: 3,
						fields: {
							height: '1028',
							width: '1713',
						},
						mediaType: 'Image',
						mimeType: 'image/jpeg',
						url:
							'https://media.guim.co.uk/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/1713.jpg',
					},
					{
						index: 4,
						fields: {
							isMaster: 'true',
							height: '1028',
							width: '1713',
						},
						mediaType: 'Image',
						mimeType: 'image/jpeg',
						url:
							'https://media.guim.co.uk/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg',
					},
				],
			},
			displayCredit: true,
		},
	],
	webPublicationDate: '2021-02-05T22:16:43.000Z',
	blocks: [
		{
			secondaryDateLine: 'Last modified on Sat 6 Feb 2021 05.27 GMT',
			blockFirstPublishedDisplay: '22.11 GMT',
			blockLastUpdated: 1612570264000,
			firstPublishedDisplay: '22.16 GMT',
			lastUpdatedDisplay: '05.27 GMT',
			blockCreatedOnDisplay: '19.05 GMT',
			blockLastUpdatedDisplay: '00.11 GMT',
			firstPublished: 1612563403000,
			createdOn: 1612551919000,
			primaryDateLine: 'Fri 5 Feb 2021 22.16 GMT',
			blockCreatedOn: 1612551919000,
			blockFirstPublished: 1612563105000,
			createdOnDisplay: '19.05 GMT',
			lastUpdated: 1612589240000,
			elements: [
				{
					elementId: 'b3b42098-76e2-412f-84bf-96248f4514d5',
					_type:
						'model.dotcomrendering.pageElements.TextBlockElement',
					html:
						'<p>When does a blip become something more major? Whatever this sticky patch is for <a href="https://www.theguardian.com/football/norwichcity" data-component="auto-linked-tag">Norwich City</a>, it is impossible to ignore the changing landscape at the top of the Championship after Swansea cut their lead at the summit to two points courtesy of goals by André Ayew and Conor Hourihane.</p>',
				},
				{
					elementId: 'c0d946ae-6041-4ac5-9134-fd8e50d6a520',
					_type:
						'model.dotcomrendering.pageElements.TextBlockElement',
					html:
						'<p>Norwich may have fired blanks for the fourth successive game but Hourihane is on quite the streak, with a superb strike here his third goal since arriving on loan from Aston Villa a fortnight ago. It looks an increasingly shrewd piece of business.</p>',
				},
				{
					elementId: '6fc07cc5-47fa-4e94-b9ea-789272ab16de',
					_type:
						'model.dotcomrendering.pageElements.TextBlockElement',
					html:
						'<p>Swansea have a game in hand on the leaders but Brentford and Reading, both of whom also have games up their sleeve, will be equally encouraged by a Norwich team stuck in a rut. Ayew capitalised on an uncharacteristic error by Tim Krul to open the scoring before Hourihane sent a rasping strike beyond the Norwich goalkeeper from distance after the interval.</p>',
				},
				{
					elementId: 'd33b86c5-49a4-4bb7-960b-fd63d3db8e54',
					role: 'thumbnail',
					prefix: 'Related: ',
					_type:
						'model.dotcomrendering.pageElements.RichLinkBlockElement',
					text:
						"Tim Krul: 'The way we play at Norwich is similar to Holland'",
					url:
						'https://www.theguardian.com/football/football-league-blog/2021/jan/29/tim-krul-way-we-play-norwich-similar-holland-netherlands-goalkeeper',
				},
				{
					elementId: '1b4ac80f-ece2-4009-90b1-d82de3fe89e3',
					_type:
						'model.dotcomrendering.pageElements.TextBlockElement',
					html:
						'<p>Swansea should have had a late penalty too, but the referee Simon Hooper waved away appeals despite Ben Gibson appearing to fell the substitute Jordan Morris after Grant Hanley collided with the all-action Connor Roberts.</p>',
				},
				{
					elementId: '6c8c6fd6-51cf-4955-a964-1aacd0588bb5',
					_type:
						'model.dotcomrendering.pageElements.TextBlockElement',
					html:
						'<p>On the eve of this game, Swansea’s unpopular American owners gave a rare interview in which they broke their silence on a multitude of longstanding issues but also made a point of stressing they have not been “taking a victory lap” on the back of their impressive start under Steve Cooper.</p>',
				},
				{
					elementId: '38e8b5fb-ccef-41ff-8333-61d2f3349bc6',
					_type:
						'model.dotcomrendering.pageElements.TextBlockElement',
					html:
						'<p>“There were no expectations at the start of the season so I think it would be unfair to start doing it [building them] now with 19 games to go,” Cooper said. “There are clubs not even in the top 10 with much more resources than us but we’re going well and enjoying the journey and that’s how we work.”</p>',
				},
				{
					elementId: '9ac04414-8163-4108-b59f-4afae80b6ec2',
					_type:
						'model.dotcomrendering.pageElements.TextBlockElement',
					html:
						'<p>Perhaps it was kidology but Daniel Farke had been at pains to play down the significance of the occasion after stuttering to a point at Millwall on Tuesday. Todd Cantwell, among those of interest to the watching England Under-21s manager Aidy Boothroyd, showed touches of class, setting Teemu Pukki free with a wonderfully weighted pass and later Kenny McLean after twirling away from Matt Grimes but the killer instinct again eluded them.</p>',
				},
				{
					elementId: 'aa3281d8-80a2-48c8-9d6f-0208310caa4f',
					_type:
						'model.dotcomrendering.pageElements.TextBlockElement',
					html:
						'<p>Swansea seized the advantage three minutes before the interval but the goal was a tragicomedy from a Norwich perspective. Krul flapped at Roberts’ in-swinging corner and when the ball dropped, Marc Guehi, another player on Boothroyd’s radar, scooped the ball away from the Norwich goalkeeper’s grasp, allowing Swansea to feast on the leftovers. Jake Bidwell tried his luck and then Ayew fired in his ninth goal of the season. Farke sought a response and Freddie Woodman saved superbly to keep out Grant Hanley’s header on the brink of the interval after the captain met Przemyslaw Placheta’s free-kick.</p>',
				},
				{
					elementId: '953e8b5b-05fe-49dc-b810-8a3dc976a72c',
					_type:
						'model.dotcomrendering.pageElements.TextBlockElement',
					html:
						'<p>Krul came out early to limber up for the second half but, before Norwich had a chance to write the wrongs, they found themselves two goals down. Jay Fulton gobbled up possession following a loose pass by McLean and played a sliderule pass infield to Hourihane, who joined on loan last month in search of regular game time. The midfielder steadied himself with first touch and then arrowed a piercing left-footed strike into the corner with his second.</p>',
				},
				{
					elementId: 'c4b4804b-5bf0-4683-9644-6a4d6e537a48',
					isThirdPartyTracking: false,
					safe: true,
					alt: 'Fiver',
					_type:
						'model.dotcomrendering.pageElements.EmbedBlockElement',
					html:
						'<iframe id="the-fiver" name="the-fiver" src="https://www.theguardian.com/email/form/plaintone/the-fiver" scrolling="no" seamless="" class="iframed--overflow-hidden email-sub__iframe" height="52px" frameborder="0" data-component="email-embed--the-fiver"></iframe>',
					source: 'The Guardian',
					sourceDomain: 'theguardian.com',
					isMandatory: false,
				},
				{
					elementId: 'cb297a8e-0f51-490e-80b9-cdb180f29114',
					_type:
						'model.dotcomrendering.pageElements.TextBlockElement',
					html:
						'<p>“We didn’t think he was going to come in and score three goals in first three league games, but we’ll take it,” said Cooper. “As soon as it fell to Conor I think everybody in the stadium thought ‘there’s a good chance of this going in.’ Once we lost Morgan [Gibbs-White, who returned to Wolves], I felt we needed a player you fancy to get goals. Conor’s numbers are really good.”</p>',
				},
				{
					elementId: '0077be0d-370b-4264-9c4a-5fda5239320e',
					_type:
						'model.dotcomrendering.pageElements.TextBlockElement',
					html:
						'<p>Krul shook his head in disbelief and Farke admitted his players are hurting. “When you lose such a spotlight game, of course, you are disappointed,” he said. “I will allow my players to be disappointed because it’s important to feel this and be greedy for this next game. We want this winning feeling back.”</p>',
				},
			],
			id: '601d96ef8f0862592e4b23ca',
		},
	],
	linkedData: [
		{
			'@type': 'NewsArticle',
			'@context': 'https://schema.org',
			'@id':
				'https://amp.theguardian.com/football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top',
			publisher: {
				'@type': 'Organization',
				'@context': 'https://schema.org',
				'@id': 'https://www.theguardian.com#publisher',
				name: 'The Guardian',
				url: 'https://www.theguardian.com/',
				logo: {
					'@type': 'ImageObject',
					url:
						'https://uploads.guim.co.uk/2018/01/31/TheGuardian_AMP.png',
					width: 190,
					height: 60,
				},
				sameAs: [
					'https://www.facebook.com/theguardian',
					'https://twitter.com/guardian',
					'https://www.youtube.com/user/TheGuardian',
				],
			},
			isAccessibleForFree: true,
			isPartOf: {
				'@type': ['CreativeWork', 'Product'],
				name: 'The Guardian',
				productID: 'theguardian.com:basic',
			},
			image: [
				'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=b8519d3db69446bfb443279cd19db7b5',
				'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=4d76500f0c4bff87eb6979e12fc4eaf4',
				'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=4933194a6d7519d92ed3cf410aa9f8a8',
				'https://i.guim.co.uk/img/media/cc1d3dc14ab9104587323ef12ac477004b369637/67_36_1713_1028/master/1713.jpg?width=1200&quality=85&auto=format&fit=max&s=56ea2121d733fa61be9fa2792b52aefa',
			],
			author: [
				{
					'@type': 'Person',
					name: 'Ben Fisher',
					sameAs: 'https://www.theguardian.com/profile/ben-fisher',
				},
			],
			datePublished: '2021-02-05T22:16:43.000Z',
			headline:
				'André Ayew sparks Swansea victory over Norwich to close gap at top',
			dateModified: '2021-02-06T05:27:20.000Z',
			mainEntityOfPage:
				'https://www.theguardian.com/football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top',
		},
		{
			'@type': 'WebPage',
			'@context': 'https://schema.org',
			'@id':
				'https://www.theguardian.com/football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top',
			potentialAction: {
				'@type': 'ViewAction',
				target:
					'android-app://com.guardian/https/www.theguardian.com/football/2021/feb/05/andre-ayew-sparks-swansea-victory-over-norwich-to-close-gap-at-top',
			},
		},
	],
	webPublicationDateDisplay: 'Fri 5 Feb 2021 22.16 GMT',
	shouldHideAds: false,
	webTitle:
		'André Ayew sparks Swansea victory over Norwich to close gap at top',
	isSpecialReport: false,
	isCommentable: true,
	keyEvents: [],
	config: {
		ajaxUrl: 'https://api.nextgen.guardianapps.co.uk',
		discussionApiUrl: 'https://discussion.theguardian.com/discussion-api',
		idApiUrl: 'https://idapi.theguardian.com',
		sentryPublicApiKey: '344003a8d11c41d8800fbad8383fdc50',
		sentryHost: 'app.getsentry.com/35463',
		dcrSentryDsn:
			'https://1937ab71c8804b2b8438178dfdd6468f@sentry.io/1377847',
		switches: {
			abCommercialCmpCustomise: true,
			prebidAppnexusUkRow: true,
			prebidTrustx: true,
			scAdFreeBanner: true,
			enableSentryReporting: true,
			lazyLoadContainers: true,
			adFreeStrictExpiryEnforcement: false,
			remarketing: true,
			emailSignupLabNotes: true,
			registerWithPhone: false,
			lotame: true,
			targeting: true,
			emailInlineInFooter: true,
			prebidPangaea: true,
			adomik: true,
			facebookTrackingPixel: true,
			serviceWorkerEnabled: false,
			iasAdTargeting: true,
			extendedMostPopular: true,
			prebidAnalytics: true,
			idEmailSignInUpsell: false,
			doubleclickYoutubeAdFree: true,
			imrWorldwide: true,
			membershipEngagementBannerBlockUs: false,
			prebidAppnexusInvcode: true,
			prebidAppnexus: true,
			enableDiscussionSwitch: true,
			consentManagement: true,
			prebidXaxis: true,
			oldTlsSupportDeprecation: true,
			abContributionsEpicAskFourEarning: true,
			discussionAllPageSize: true,
			emailSignupEuRef: true,
			prebidUserSync: true,
			audioOnwardJourneySwitch: true,
			breakingNews: true,
			externalVideoEmbeds: true,
			simpleReach: true,
			emailInArticleOutbrain: true,
			carrotTrafficDriver: true,
			geoMostPopular: true,
			abFebruaryMomentBannerThankYou: false,
			weAreHiring: true,
			relatedContent: true,
			thirdPartyEmbedTracking: true,
			commercialPageViewAnalytics: true,
			prebidAdYouLike: true,
			membershipEngagementBanner: true,
			mostViewedFronts: true,
			googleSearch: true,
			membershipEngagementBannerBlockAu: false,
			commercial: true,
			plistaAu: true,
			prebidSonobi: true,
			membershipEngagementBannerBlockUk: false,
			idProfileNavigation: true,
			discussionAllowAnonymousRecommendsSwitch: false,
			scrollDepth: true,
			epicTestsFromGoogleDocs: true,
			youtubeRelatedVideos: true,
			webFonts: true,
			abFebruaryMomentBannerCopy: true,
			prebidImproveDigital: true,
			abCommercialPrebidSafeframe: true,
			ophan: true,
			abAcquisitionsEpicAlwaysAskIfTagged: true,
			crosswordSvgThumbnails: true,
			weather: true,
			hostedVideoAutoplay: true,
			emailInArticleGtoday: true,
			engagementBannerTestsFromGoogleDocs: false,
			prebidS2sozone: true,
			abAdblockAsk: true,
			prebidPubmatic: true,
			serverShareCounts: true,
			autoRefresh: true,
			enhanceTweets: true,
			prebidIndexExchange: true,
			prebidOpenx: true,
			tourismAustralia: true,
			emailInArticle: true,
			idCookieRefresh: true,
			sharingComments: true,
			discussionPageSize: true,
			smartAppBanner: true,
			boostGaUserTimingFidelity: false,
			historyTags: true,
			videojs: true,
			surveys: true,
			abCommercialAdVerification: false,
			inizio: true,
			acast: true,
		},
		shortUrlId: '/p/4k83z',
		abTests: {},
		dfpAccountId: '',
		commercialBundleUrl:
			'https://assets.guim.co.uk/javascripts/3d3cbc5f29df7c0cdd65/graun.dotcom-rendering-commercial.js',
		revisionNumber: '62cf0d6e4609276d37e09fd596430fbf8b629418',
		isDev: false,
		googletagUrl: '//www.googletagservices.com/tag/js/gpt.js',
		stage: 'DEV',
		frontendAssetsFullURL: 'https://assets.guim.co.uk/',
		hbImpl: {
			prebid: false,
			a9: false,
		},
		adUnit: '/59666047/theguardian.com/film/article/ng',
		isSensitive: false,
		videoDuration: 0,
		edition: '',
		section: '',
		sharedAdTargeting: {},
		keywordIds: '',
		showRelatedContent: false,
		pageId: '',
		webPublicationDate: 1579185778186,
		headline: '',
		author: '',
		keywords: '',
		series: '',
		contentType: '',
		isPaidContent: false,
		discussionD2Uid: 'testD2Header',
		discussionApiClientHeader: 'testClientHeader',
		ampIframeUrl:
			'https://assets.guim.co.uk/data/vendor/a994b749adae30cd58f0e84c8fa28013/amp-iframe.html',
		isPhotoEssay: false,
		isLiveBlog: false,
		isLive: false,
	},
};
