import { App } from 'aws-cdk-lib';
import { Template } from 'aws-cdk-lib/assertions';
import { RenderingApp } from './rendering-app';

/**
 * These tests make sure that the cloudformation template being generated by CDK has not deviated
 * from the cloudformation snapshot that has been checked into our repository.
 */
describe('The RenderingApp stack', () => {
	it('matches the snapshot', () => {
		const app = new App();
		const stack = new RenderingApp(app, 'ArticleRendering', {
			stage: 'TEST',
			app: 'article',
			minCapacity: 1,
			maxCapacity: 4,
			instanceType: 't4g.micro',
		});
		const template = Template.fromStack(stack);
		expect(template.toJSON()).toMatchSnapshot();
	});
});
