// flow-typed signature: f45432a4e3c260f20140b31b3ce67480
// flow-typed version: <<STUB>>/@guardian/pasteup_v0.1.0-alpha.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@guardian/pasteup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@guardian/pasteup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@guardian/pasteup/breakpoints' {
  declare module.exports: any;
}

declare module '@guardian/pasteup/fonts' {
  declare module.exports: any;
}

declare module '@guardian/pasteup/mixins' {
  declare module.exports: any;
}

declare module '@guardian/pasteup/palette' {
  declare module.exports: any;
}

// Filename aliases
declare module '@guardian/pasteup/breakpoints.js' {
  declare module.exports: $Exports<'@guardian/pasteup/breakpoints'>;
}
declare module '@guardian/pasteup/fonts.js' {
  declare module.exports: $Exports<'@guardian/pasteup/fonts'>;
}
declare module '@guardian/pasteup/mixins.js' {
  declare module.exports: $Exports<'@guardian/pasteup/mixins'>;
}
declare module '@guardian/pasteup/palette.js' {
  declare module.exports: $Exports<'@guardian/pasteup/palette'>;
}
declare module '@guardian/pasteup/icons/x.svg' {
    declare module.exports: $Exports<'@guardian/pasteup/icons/x.svg'>;
}
declare module '@guardian/pasteup/icons/arrow-right.svg' {
    declare module.exports: $Exports<'@guardian/pasteup/icons/arrow-right.svg'>;
}
declare module '@guardian/pasteup/logos/the-guardian.svg' {
    declare module.exports: $Exports<'@guardian/pasteup/logos/the-guardian.svg'>;
}
