name: 🧪 Deploy CODE AB Testing Config

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ab-testing-checks.yml
    with:
      save_build_artifact: true
    secrets:
      FASTLY_AB_TESTING_CONFIG: ${{ secrets.FASTLY_CODE_AB_TESTING_CONFIG }}
      FASTLY_API_TOKEN: ${{ secrets.FASTLY_CODE_API_TOKEN }}

  deploy:
    name: Deploy CODE
    needs: ci
    uses: ./.github/workflows/ab-testing-deploy.yml
    with:
      stage: code
    secrets:
      FASTLY_AB_TESTING_CONFIG: ${{ secrets.FASTLY_CODE_AB_TESTING_CONFIG }}
      FASTLY_API_TOKEN: ${{ secrets.FASTLY_CODE_API_TOKEN }}
