name: 🦕 AB testing UI
on:
  pull_request:
    paths:
      - 'ab-testing/**'
      - '.github/workflows/ab-testing-*.yml'
  push:
    branches:
      - main
    paths:
      - 'ab-testing/**'
      - '.github/workflows/ab-testing-*.yml'

jobs:
  build-ui:
    name: AB testing UI build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ab-testing/frontend
    steps:
      - uses: actions/checkout@v5

      # https://github.com/denoland/setup-deno#latest-stable-for-a-major
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.3
      - name: Install
        run: deno install
      - name: Build
        run: deno run build
      - name: Save build
        uses: actions/upload-artifact@v5
        with:
          name: ui-build
          path: ab-testing/frontend/output/ab-tests.html
          if-no-files-found: error

  riff-raff:
    name: AB testing Riffraff upload
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node
        uses: ./.github/actions/setup-node-env

      - name: Fetch build
        uses: actions/download-artifact@v5.0.0
        with:
          name: ui-build
          path: output/ab-tests.html

      - name: Riff-Raff Upload
        uses: guardian/actions-riff-raff@v4.1.9
        with:
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: dotcom:ab-testing
          configPath: ab-testing/riff-raff.yaml
          contentDirectories: |
            admin/ab-testing:
              - output/ab-tests.html
