name: 🦕 AB testing UI
on:
  workflow_call:

jobs:
  build-ui:
    name: AB testing UI build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ab-testing/frontend
    steps:
      - uses: actions/checkout@v5

      # https://github.com/denoland/setup-deno#latest-stable-for-a-major
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.3
      - name: Install
        run: deno install
      - name: Build
        run: deno run build
      - name: Save build
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ab-testing-ui-build
          path: ab-testing/frontend/output/ab-tests.html
          if-no-files-found: error
