on:
  workflow_call:
    inputs:
      container-image:
        description: 'Image used by DCR service'
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    services:
      DCR:
        image: ${{ inputs.container-image }}
        ports:
          - 9000:9000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node environment
        uses: ./.github/actions/setup-node-env

      - name: Validate AMP
        run: make ampValidation
        working-directory: dotcom-rendering
