name: DCR CICD

on:
  merge_group:
    types: [checks_requested]
  push:

jobs:
  production-container:
    permissions:
      contents: read
      id-token: write # Required to exchange for AWS credentials using OIDC
    uses: ./.github/workflows/container-production.yml
    secrets:
      GU_RIFF_RAFF_ROLE_ARN: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

  container:
    permissions:
      packages: write
    needs: [production-container]
    uses: ./.github/workflows/container.yml
    with:
      production-image-digest: ${{ needs.production-container.outputs.imageDigest }}

  prettier:
    uses: ./.github/workflows/prettier.yml

  jest:
    uses: ./.github/workflows/jest.yml

  lint:
    uses: ./.github/workflows/lint.yml

  islands:
    uses: ./.github/workflows/check-islands.yml

  playwright:
    needs: [container]
    uses: ./.github/workflows/playwright.yml
    with:
      container-image: ${{ needs.container.outputs.container-image }}

  publish:
    permissions:
      id-token: write
      contents: read
      pull-requests: write # required by riff-raff action
    needs: [container, islands, prettier, jest, lint, playwright]
    uses: ./.github/workflows/publish.yml
    with:
      container-image: ${{ needs.container.outputs.container-image }}
    secrets:
      GU_RIFF_RAFF_ROLE_ARN: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
