on:
  workflow_call:
    secrets:
      GU_ARTIFACTS_ROLE_ARN:
        required: true
    inputs:
      production-image-digest:
        description: 'Digest of DCR image in AWS ECR'
        required: true
        type: string

jobs:
  playwright:
    # We currently only publish an ARM64 Docker image, we have to match to run it
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      id-token: write # Required to exchange for AWS credentials using OIDC
    strategy:
      fail-fast: false
      matrix:
        # keep aligned with the number of shards used by `playwright test`
        group: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Node environment
        uses: ./.github/actions/setup-node-env

      - name: Pull image
        id: pull-image
        uses: guardian/actions-publish-image/pull@multi-action
        with:
          roleArn: ${{ secrets.GU_ARTIFACTS_ROLE_ARN }}
          imageIdentifier: ${{ inputs.production-image-digest }}
          appName: dotcom-rendering

      # `GU_STAGE=CI` defaults DCR to reference JS assets from the local server, rather than the CDN.
      - name: Start DCR in a container
        run: |
          docker run -d \
            -p 9000:9000 \
            -e "GU_APP=article-rendering" \
            -e "GU_STACK=frontend" \
            -e "GU_STAGE=CI" \
            -e "DISABLE_LOGGING_AND_METRICS=true" \
            ${{ steps.pull-image.outputs.imageUri }}

      - name: Turn off mandb updates
        run: |
          sudo mv /usr/bin/mandb /usr/bin/mandb-OFF
          sudo cp -p /bin/true /usr/bin/mandb

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium
        working-directory: ./dotcom-rendering

      - name: Run Playwright
        run: pnpm playwright test --shard=${{ matrix.group }}/8
        working-directory: ./dotcom-rendering
        env:
          NODE_ENV: production

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: playwright-report-${{ matrix.group }}
          path: ./dotcom-rendering/playwright-report
          retention-days: 5
