on:
  workflow_call:
    inputs:
      container-image:
        description: 'Image used by DCR service'
        required: true
        type: string

jobs:
  playwright:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # keep aligned with the number of shards used by `playwright test`
        group: [1, 2, 3, 4, 5, 6, 7, 8]
    services:
      DCR:
        image: ${{ inputs.container-image }}
        ports:
          - 9000:9000
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node environment
        uses: ./.github/actions/setup-node-env

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium
        working-directory: ./dotcom-rendering

      - name: Run Playwright
        run: pnpm playwright test --shard=${{ matrix.group }}/8
        working-directory: ./dotcom-rendering
        env:
          NODE_ENV: production

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.group }}
          path: ./dotcom-rendering/playwright-report
          retention-days: 5
