name: ⏰ Scheduled daily jobs
on:
  schedule:
    # Every work day of the week at 08:08
    - cron: '8 8 * * MON-FRI'

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  scheduled:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/denoland/setup-deno#latest-stable-for-a-major
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v1.44

      - name: Thrasher tracker
        working-directory: scripts/deno
        run: |
          deno run \
            --allow-read \
            --allow-net \
            --allow-env=HOME,GITHUB_TOKEN \
            --allow-sys=homedir \
            thrasher-tracker.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: iFrame titles tracker
        working-directory: scripts/deno
        run: |
          deno run \
            --allow-read \
            --allow-net \
            --allow-env=HOME,GITHUB_TOKEN,CAPI_KEY \
            --allow-sys=homedir \
            iframe-titles.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CAPI_KEY: ${{ secrets.CAPI_KEY }}
